### ISSUE TITLE
UnsupportedMediaType error (CDP4 + OCDT WSP)

### ISSUE THREAD

**Issue by s-jahnke** [RHEAGROUP/CDP4-IME-Community-Edition#1]
Dear all,

I experienced an issue during my first attempt to use the desktop version of CDP4 (CDP4IME-CE-1.0.3) in combination with a local OCDT WSP Server (WSP v2.0.5).

After sucesfully connecting to the server, the tool always throws the same error when I try to add any value (new user, organization, role...), see also screenshot attached: 

> The CDP4 Services replied with code UnsupportedMediaType: Unsupported Media Type

![cdp4_error](https://user-images.githubusercontent.com/35369745/34874595-f9b031fe-f799-11e7-87d4-822d693239c3.png)

I am not an experienced user in CDP nor an expert in OCDT Services so it could also be a faulty setup from my side.

Thanks for your help!

Cheers,
Stephan

**Comment by samatrhea** [comment]
Dear Stephan,

Thanks for posting this bug report, we will investigate and get back to you ASAP. Just a short question, what "DAL" did you select in the "login" form:: the **WSPDal** or the **CDP4ServicesDal**. In principle when communicating with the OCDT WSP the WSPDal needs to be selected.

**Comment by s-jahnke** [comment]
In the "Data Source Selection" dialog I selected "OCDT WSP" as "Data Source"...so I think this should be ok, right?
Thanks for the support!

**Comment by samatrhea** [comment]
We have been able to reproduce the issue, working on it

**Comment by samatrhea** [comment]
Posted Bug on [CDP4-SDK](https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues/3)
