### ISSUE TITLE
Publication browser - parameter row for item with components shouldn't show value

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#101]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

In the Publication browser - parameter rows for item with components shouldn't show a value. e.g. for compound or array parameters, the row now shows the value for the first component. The values should be left empty.

![image](https://user-images.githubusercontent.com/35371313/54289833-25a77880-45aa-11e9-8251-32d913d9c6b0.png)

### Steps to Reproduce

in a model, change values for multiple components for a parameter with components and inspect the publication browser.

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [ ] CDP4-IME: 2.0.2
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by alexatrhea** [comment]
State and option dependent rows have not been confirmed for this issue. Reopened.
