### ISSUE TITLE
Copy modelcode of a Parameter on Elements in the ProductTree to clipboard using the mouse

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#103]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
From the product tree, provide a context menu item to the user to copy to the clipoard the model-code of the nested-element that is selected. The product tree does not contain nested-elements, only displays the items as if they are a nestedelementtree. So, the copied model-code should not _just_ be the model-code of the selected item.

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [ ] CDP4-IME: 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by mmilitaru** [comment]
I would like to make it clear. Which node type needs to have the contextual menu? It should be only for the Parameter type?

**Comment by samatrhea** [comment]
@mmilitaru the ElementDefinition tree and the Product Tree do not contain ParameterTypes, they contain Parameters, ParameterOverrides and ParameterSubscriptions. So, the context menu should be on those 3 kinds of things.
