### ISSUE TITLE
Refactor ValidationService to be MEF injected and extensible from code

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#106]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Currently the `ValidationService` is implemented as a static class, where the `ValidationRule`s are also statically _loaded_. This means that when we want to change the `ValidationRule`s we basically have to update the `CDP4Composition` and recompile the whole application. It is good to have basic rules that should always apply, but adding new rules should be possible from plugins that may need it specifically,

The proposed improvement is to allow developers to add or override existing `ValidationRules` from code. This can be achieved by implementing the `ValidationService` as a MEF injected service and to somehow expose the list of ValidationRules, so new Rules can be added, or existing rules can be overriden for a specific module/plugin. This last bit is important, when a ValidationRule for a property is overriden for a specific plugin, this should not impact the validation for the other plugins.
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 2.1.0

**Comment by alexatrhea** [comment]
This task is too large and can be split into a few smaller tasks, such as:

1. Refactor into a service.
2. Make extensible.
3. Implement plugin specific overrides.
