### ISSUE TITLE
Add the shortname of the parametertype to the list of SimpleParameterValues on the Requirements Dialog

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#107]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The Requirements dialog shows the list of SimpleParameterValues. This list should show in the first column the shortname of the referenced ParameterType.

### Steps to Reproduce
NA

### Logs

  - [x] There are no logs regarding the issue
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 2.1.0

**Comment by alexatrhea** [comment]
#206

**Comment by MartinFijneman** [comment]
verified, short name available
