### ISSUE TITLE
Parametric constraint for a requirement doesn't take info from complete chain of RDLs

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#109]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Parametric constraint for a requirement doesn't take info from complete chain of RDLs, see description of steps below

### Steps to Reproduce

setup:
* create new site RDL ("newSiteRDL") based on generic RDL
* added several new parameter types to newSiteRDL
* create an engineering model that is using the newSiteRDL
* create a requirement in a requirement specification in this model
* try to add a parametric constraint to the requirement

problem:
* the only parameters that can be selected for the parametric constraint are the parameter types from newSiteRDL (so only limited set)

Note that trying to add a Simple Parameter Value, all the parameter types from the generic RDL are available, as expected.

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [ ] CDP4-IME: 2.0.2.0
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [X] Windows OS (32/64 bit): 64 bit
  - [ ] Additional information:

**Comment by alexatrhea** [comment]
Fixed in 7bb1974
