### ISSUE TITLE
Moving requirement between requirements groups not working as expected

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#116]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Moving requirement between requirements groups not working as expected:
drop target is shown, but action is not performed, resulting move not performed upon release of requirement.

Noticed problem in setting up a model for a project (model available).
Issue reproducible, reference testing performed on public server, log files included.

### Steps to Reproduce

* create an engineering model and open this
* open requirements browser
* create requirements specification
* create several requirements groups (1, 2, 3)
* create requirement directly under requirements specification: in log files this was "Req1" (creation of requirement not in log file, was already created earlier)
* create requirement under a requirements group: in attached log files this was "Test2"

Now try to move the requirements, problems are:
for "Req1":
*  can be moved from the specification to one of the groups
* after this, can be moved between the groups
* Problem: cannot be moved back under the specification node

for "Test2":
* can be moved under the specification node
* can be moved back to the original group
* Problem: cannot be moved to another group

### Logs

  - [ ] There are no logs regarding the issue
  - [X] I have attached a log file or included the relevant section in this issue  

Initial log file with creation of groups, requirement "Test2" and performing several moves of requirements.
  
[CDP4IME - Moving requirement not possible 1.log](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/3064709/CDP4IME.-.Moving.requirement.not.possible.1.log)

Additional log file with trying additional moves of both requirements, with results as described in steps to reproduce.

[CDP4IME - Moving requirement not possible 2.log](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/3064715/CDP4IME.-.Moving.requirement.not.possible.2.log)

### System Configuration

- CDP4 version:
  - [ ] CDP4-IME: 3.0.0
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [X] Windows OS (32/64 bit): 64 bit windows 10
  - [ ] Additional information:

**Comment by samatrhea** [comment]
I created on the development server at https://cdp4services-dev.rheagroup.com a test model called GH116. In this model i created 1 requirements specification, 3 groups and 2 requirements.

see image below

![image](https://user-images.githubusercontent.com/22165725/55961657-a8862680-5c6f-11e9-96f2-90d231bbc82c.png)

While testing the described issue i noticed that i can move both requirements provided the target, either a specification or a group is empty. If it is not empty, so already contains a requirement, the move does not work as expected. I continue the hunt for a solution.

**Comment by naronatrhea** [comment]
@MartinFijneman @samatrhea  did you have a order-parater-type set in the configuration of CDP4?
