### ISSUE TITLE
ElementDefinitionBrowser icon for option and state are not showing

### ISSUE THREAD

**Issue by naronatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#117]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of the CDP4-IME
- [ ] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
In the ElementDefinitionBrowser icons for option and state do not seem to be showing anymore

### Steps to Reproduce
create a parameter with option/state-dependency and see that icons are missing

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [ ] CDP4-IME: 3.0.0.0
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by alexatrhea** [comment]
closing duplicate to #225
