### ISSUE TITLE
Relationship Matrix - as a user, I want to have additional controls over the selection to get expected result

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#118]
### Prerequisites
- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Relationship Matrix - as a user, I want to have additional controls over the selection to get expected result.

10-25 gives a lot of possibilities and also quite some freedom in modelling. 

It would help for the relationship matrix if the selection can provide several (combinations of) selection and filtering for the categories that allow a user to bring in the selection some implicit "hierarchy" to get the results he/she expects, based on knowledge of the model.

Currently, the results are given when an item confirms to any of the provided categories, which can give some unexpected results in the list, based on the modelling (i.e. very situation-dependent).

TBD how this can best be achieved:

* having multiple selection criteria instead of only one in a more or less stepped approach or progressive filtering, so that the items at a lower level are always a limited subset of the higher level items

* having multiple selection criteria, and allowing a user to provide logical operators on these criteria (AND, OR, XOR), giving the user the freedom to make combinations of any required subset of items for the result shown

With this, the result will still depend highly on the applied modelling, and the user's knowledge of this, but in any case gives the user more possibilities to get an expected result.

### Logs

  - [X] There are no logs regarding the issue

  
### System Configuration

- CDP4 version:
  - [ ] CDP4-IME: 3.0.1
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by samatrhea** [comment]
@MartinFijneman can you give an explicit example so that it is easier to picture the end result that you are aiming for?
