### ISSUE TITLE
CDP4 v3.0.1 crashes on first run when RHEA\CDP4 folder is missing from %APPDATA%

### ISSUE THREAD

**Issue by hpdekoning** [RHEAGROUP/CDP4-IME-Community-Edition#119]
### Prerequisites

- [ x] I have written a descriptive issue title
- [ x] I have verified that I am running the latest version of the CDP4-IME
- [ x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Right after starting up, an exception is reported that "C:\Users\<username>\AppData\Roaming\RHEA\CDP4\CDP4RelationshipMatrix.settings.json" can not be found. Manually adding folders RHEA\CDP4 resolves the issue.

### Steps to Reproduce
See above.

### Logs
-----------------------------
[General Info]

Application: CDP4IME
Version:     3.0.1.0
Region:      English (United Kingdom)
Machine:     <hostname>
User:        <username>
Date: 2019-04-16
Time: 15:45

User Explanation:

<username> said ""
-----------------------------

[Exception Info 1]

Top-level Exception
Type:        System.ComponentModel.Composition.CompositionException
Message:     The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.

1) Could not find a part of the path 'C:\Users\<username>\AppData\Roaming\RHEA\CDP4\CDP4RelationshipMatrix.settings.json'.

Resulting in: An exception occurred while initializing module 'RelationshipMatrixModule'. 
    - The exception message was: Could not find a part of the path 'C:\Users\<username>\AppData\Roaming\RHEA\CDP4\CDP4RelationshipMatrix.settings.json'.
    - The Assembly that the module was trying to be loaded from was:CDP4RelationshipMatrix, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null
    Check the InnerException property of the exception for more information. If the exception occurred while creating an object in a DI container, you can exception.GetRootException() to help locate the root cause of the problem. 
  

Resulting in: An exception occurred while calling the 'OnImportsSatisfied' method on type 'Microsoft.Practices.Prism.MefExtensions.Modularity.MefModuleManager'.

Resulting in: Cannot activate part 'Microsoft.Practices.Prism.MefExtensions.Modularity.MefModuleManager'.
Element: Microsoft.Practices.Prism.MefExtensions.Modularity.MefModuleManager -->  Microsoft.Practices.Prism.MefExtensions.Modularity.MefModuleManager -->  AssemblyCatalog (Assembly="Microsoft.Practices.Prism.MefExtensions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35")

Resulting in: Cannot get export 'Microsoft.Practices.Prism.MefExtensions.Modularity.MefModuleManager (ContractName="Microsoft.Practices.Prism.Modularity.IModuleManager")' from part 'Microsoft.Practices.Prism.MefExtensions.Modularity.MefModuleManager'.
Element: Microsoft.Practices.Prism.MefExtensions.Modularity.MefModuleManager (ContractName="Microsoft.Practices.Prism.Modularity.IModuleManager") -->  Microsoft.Practices.Prism.MefExtensions.Modularity.MefModuleManager -->  AssemblyCatalog (Assembly="Microsoft.Practices.Prism.MefExtensions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35")

Source:      System.ComponentModel.Composition
Stack Trace: at System.ComponentModel.Composition.Hosting.CompositionServices.GetExportedValueFromComposedPart(ImportEngine engine, ComposablePart part, ExportDefinition definition)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportedValue(CatalogPart part, ExportDefinition export, Boolean isSharedPart)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.CatalogExport.GetExportedValueCore()
   at System.ComponentModel.Composition.Primitives.Export.get_Value()
   at System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[T](Export export)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValueCore[T](String contractName, ImportCardinality cardinality)
   at Microsoft.Practices.Prism.MefExtensions.MefBootstrapper.InitializeModules()
   at Microsoft.Practices.Prism.MefExtensions.MefBootstrapper.Run(Boolean runWithDefaultConfiguration)
   at CDP4IME.App.RunInReleaseMode()

-----------------------------

[Assembly Info]

mscorlib, Version=4.0.0.0
Microsoft.Practices.Prism.MefExtensions, Version=5.0.0.0
NLog, Version=4.0.0.0
WindowsBase, Version=4.0.0.0
CDP4Composition, Version=3.0.0.0
System.ComponentModel.Composition, Version=4.0.0.0
Microsoft.Practices.Prism.Composition, Version=5.0.0.0
System, Version=4.0.0.0
ReactiveUI, Version=6.4.0.0
System.Core, Version=4.0.0.0
CDP4Dal, Version=5.0.0.0
CDP4ShellDialogs, Version=3.0.0.0
PresentationFramework, Version=4.0.0.0
DevExpress.Xpf.Ribbon.v15.2, Version=15.2.19.0
System.Xaml, Version=4.0.0.0
DevExpress.Xpf.Core.v15.2, Version=15.2.19.0
DevExpress.Xpf.Docking.v15.2, Version=15.2.19.0
Hardcodet.Wpf.TaskbarNotification, Version=1.0.5.0
Microsoft.Practices.Prism.Mvvm, Version=1.1.1.0
System.Windows.Forms, Version=4.0.0.0
CDP4Common, Version=3.0.0.0
Microsoft.Practices.ServiceLocation, Version=1.3.0.0
System.Reactive.Linq, Version=2.2.5.0
System.Reactive.Core, Version=2.2.5.0
System.Reactive.Interfaces, Version=2.2.5.0
ExceptionReporter.WinForms, Version=2.1.0.0
PresentationCore, Version=4.0.0.0

-----------------------------

[Config Settings]

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
      <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
          <section name="DXThemeManager" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false" />
      </sectionGroup>
  </configSections>
  <startup> 
      <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />
  </startup>
  <userSettings>
      <DXThemeManager>
          <setting name="ApplicationThemeName" serializeAs="String">
              <value>Seven</value>
          </setting>
      </DXThemeManager>
  </userSettings>  
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Practices.Prism.SharedInterfaces" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.1.1.0" newVersion="1.1.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Practices.Prism.PubSubEvents" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.1.0.0" newVersion="1.1.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Practices.ServiceLocation" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.3.0.0" newVersion="1.3.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Windows.Interactivity" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.5.0.0" newVersion="4.5.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>

-----------------------------

[System Info]

Operating System
-Microsoft Windows 10 Enterprise
--CodeSet = 1252
--CSDVersion = 
--CurrentTimeZone = 120
--FreePhysicalMemory = 7939740
--OSArchitecture = 64-bit
--OSLanguage = 1033
--ServicePackMajorVersion = 0
--ServicePackMinorVersion = 0
--Version = 10.0.16299

Machine
-<hostname>
--Manufacturer = Dell Inc.
--Model = Latitude 7490
--TotalPhysicalMemory = 17053351936
--UserName = <domainname>\<username>

-----------------------------

  
### System Configuration

- CDP4 version:
  - [ x] CDP4-IME: 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by naronatrhea** [comment]
Thanks for reporting, I think this should be fixed in the next release.

**Comment by samatrhea** [comment]
The `PluginSettingsService` is the culprit, if the settings folder does not exist, it cannot create the default settings file. The code will be updated to create the `RHEA\CDP4` folder in the appdata folder in case it does not yet exist. The NLog logger is added to the `PluginSettingsService` to add logging for reading and writing the settings files.

**Comment by samatrhea** [comment]
problem fixed in `D1489`, @naronatrhea can you have a look at the fix please?
