### ISSUE TITLE
Demo server - not possible anymore to create a parameter group directly under an element definition

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#12]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

On demo server, in Marco Polo model
* until recently, no problem in creating parameter groups, worked in several model setups.
* now, in both existing models and in new models, it seems no longer possible to create a new parameter group directly under an element definition: the ok-button is not activated.
** note: it is possible to create a new group under an existing group; in this case, the ok is activated.
** note: the list for "Container" is empty, this doesn't show any of the existing parameter groups that are already in the ED.

![image](https://user-images.githubusercontent.com/35371313/39635419-c387d36c-4fbd-11e8-8d87-401820bcc973.png)

### Steps to Reproduce

Log into demo server, open model, try to create parameter group directly under an element definition.

### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 1.0.8
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [X] Windows OS (32/64 bit): 32
  - [ ] Additional information:

**Comment by samatrhea** [comment]
not related to a server, the use of ```GetContainerOfType<T``` in the ```ExecutePararameterGroup``` is incorrect.
