### ISSUE TITLE
Requirements browser - deprecated requirement should be filtered out in normal view

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#120]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of the CDP4-IME
- [ ] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Requirements browser - deprecated requirement should be filtered out in normal view

When a requirement is deprecated, currently it stays visible as it is in the Requirements browser, need to inspect the details to show its deprecated status, see picture below. 

Expected result would be that the deprecated requirement is not visible anymore in the normal view in the Requirement browser. Should only be visible when using the "show deprecated things" toggle from the View-menu, similar as in other views (e.g. for reference data).

![image](https://user-images.githubusercontent.com/35371313/56274000-347bd080-60fe-11e9-9486-3635c718474e.png)

### Steps to Reproduce

* in requirements specification, add requirement, 
* then edit to set to "deprecated"

### Logs

  - [X] There are no logs regarding the issue
  
  
### System Configuration

- CDP4 version:
  - [ ] CDP4-IME: 3.0.1
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by samatrhea** [comment]
Seems to be working on the Person and the ParameterTyoe browser, so something specific must be going on with the requirements

**Comment by samatrhea** [comment]
i have spent some time looking at this and i am at a loss, cannot figure out what the problem could be. @naronatrhea could you have a look?

**Comment by alexatrhea** [comment]
@samatrhea 

Some investigation into this by @lxatrhea yesterday leads us to believe that this is (in part at least) due to DevExpress' manner of dealing with non-leaf nodes in trees. Later versions of DE seem to have improved this, so I suggest we wait till an update has been performed to deal with this.
