### ISSUE TITLE
element definition and product tree browser - update views for ED/EU updates on categories

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#121]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

element definition and product tree browser - update views for ED/EU updates on categories

the element definition and product tree browser (in any case, but basically any other view where the categories are shown), should be updated for changes to an element definition, and its associated element usages. Currently in the UI, such a change is not visible to the user. This shows the additional category only on the ED, not on the associated EU(s).

### Steps to Reproduce

* setup simple model with 2 element definitions
* apply a category to each of the element definitions
* add one element definition as a usage to the other ED
* add a second category to the element definition

### Logs

  - [X] There are no logs regarding the issue
  
  
### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 3.0.2
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by naronatrhea** [comment]
@MartinFijneman ED and EU do not necessarily have the same categories though, how do you ant to handle this

**Comment by samatrhea** [comment]
When a specific ElementDefinition has been categorized as a `Battery` then the ElementUsage that references that ElementDefinition is also a `Battery`.

The request of @MartinFijneman is not to update any data in the database, but to show in the UI that the ElementUsage, eventhough itself is not categorized as a Battery, is indeed a battery.

For now, this only applies to ElementDefinition and ElementUsage. And this is specified in 10-25, see the following Note: 

``` 
Note 2: When an ElementDefinition is made a member of a Category through its category property, then also any ElementUsage typed by such an ElementDefinition is implied to be a member of the same Category.
```

**Comment by naronatrhea** [comment]
So maybe in the server when the categories of a ED is updated, we should also update the categories of a EU?

**Comment by samatrhea** [comment]
i don't think this is a server side fix. Its about showing the implicit info in the UI.

**Comment by samatrhea** [comment]
@MartinFijneman: we'll update the tooltip with the _extra_ categories for ElementUsages. Can you also give a hint on how you would want to see the categories of the ElementUsages on the details window?

**Comment by MartinFijneman** [comment]
@samatrhea my suggestions for this would be:
For the tooltip of an EU:
* show applied categories filtering out duplicates
* use normal font for categories that are applied to the EU directly
* use italic font for categories that are referenced from its ED

For the Inspect/Edit Element Usage dialog:
this dialog currently has 2 tabs related to categories:
* Category tab: to edit the applicable categories
* Definition Categories: to show the referenced categories from the ED
My suggestion would be to add the category information on the "Basic" tab, so that this tab shows the applied categories, this can show the "definition categories" and the "usage categories". the definition categories tab would not be needed anymore as a separate tab. For the element usage itself, the category tab would remain to change the applicable categories.
In this way, the basic tab immediately shows this important information.

**Comment by samatrhea** [comment]
unfortunately italics are not possible, i cannot play with fonts

**Comment by MartinFijneman** [comment]
for the tooltip text, if no font change is possible, then I would suggest a listing with a clear separator (e.g. semicolon or pipe) between the EU categories and the ED referenced categories

**Comment by samatrhea** [comment]
regarding the categories tab, do you want all details views to have the categories info on the basic tab? (for some views this may become very crowded...)

what we can do is show the applied categories on the basic tab, but edit the list of applied categories on the categories tab, or do you stick with the proposed -> remove categories tab and show all on basic tab?

**Comment by MartinFijneman** [comment]
My proposal was to only remove the " definition categories tab", not removing the "categories" tab. this "categories" tab is useful to edit the applied categories indeed.
So I think we are in agreement, stating my original proposal a bit more clearly:
* "Basic" tab shows an overview of the applied categories, listing the categories from the EU, and those referenced from the ED, with a clear separator between them. Also filtering out possible duplicates
* "Category" tab to edit the categories for the EU
* "Definition Categories" tab can be removed if info is indeed shown already on the "Basic" tab

**Comment by samatrhea** [comment]
progress is being made, here you can see a screenshot of the applied categories on an ElementUsage discplayed on the **basic** tab

![image](https://user-images.githubusercontent.com/22165725/56767303-aa8dd080-67ab-11e9-880e-292471e3c887.png)

**Comment by samatrhea** [comment]
the tooltips for EU in trees looks like this now:

![image](https://user-images.githubusercontent.com/22165725/56769187-b9c34d00-67b0-11e9-9f37-a9d5e00b3ec9.png)

notice that also the supercategories are included between curly braces

**Comment by samatrhea** [comment]
@alexatrhea diff up at D1494
