### ISSUE TITLE
Create parameterized category rule-dialog: doens't open, error is thrown

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#122]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Create parameterized category rule-dialog: doens't open, error is thrown

### Steps to Reproduce

Reproducible bug:
* open a model, go to Reference Data tab
* open Rules
* select "create parameterized category rule"

The dialog doesn't appear to create a new rule, an error is thrown.

### Logs

  - [X] There are no logs regarding the issue
  
Error log message:

> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: The added item already exists

### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 3.0.2
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by samatrhea** [comment]
Possible Categories population incorrect, is fixed, diff up at D1490
