### ISSUE TITLE
Tray Icon does not dispose correctly

### ISSUE THREAD

**Issue by alexatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#125]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The tray Icon does not clear from the tray when application shuts down. Once the mouse hovers over it, it disappears. Investigate whether additional `Dispose()` calls need to be made. After running a few times, the tray becomes full of icons.

### Steps to Reproduce
Run application and shut down.
### Logs

  - [x] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 3.0.3
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by samatrhea** [comment]
do you notice this during development and running the CDP4-IME from Visual Studio (while debugging) or have you also noticed this while using the application in production?

@MartinFijneman have you also noticed this?

**Comment by alexatrhea** [comment]
Seems to be debug issue only. Closing.
