### ISSUE TITLE
Category outside of chain of RDL can be drag-and-dropped on things, leading to incorrect hoovertext

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#127]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Category outside of chain of RDL can be drag-and-dropped on things, leading to incorrect hoovertext
This drag-and-drop is shown as allowed currently, while it should show a "stop" sign, indicating that this is not possible.

### Steps to Reproduce

Preparations:
* Create a SiteRDL, based on the generic RDL
* create an extra category in the SiteRDL, applicable to e.g. element definitions, element usages, requirements
* create a model using the new test SiteRDL, with e.g. element definitions and requirements - check that these can apply the new extra category from this SiteRDL
* create a model using the generic SiteRDL
* create e.g. an element definition and/or a requirement in the model using the generic SiteRDL
* edit the element definition and/or requirement - this cprrectly doesn't show the extra new category from the new SiteRDL on the category tab

Steps leading to problem:
* drag-and-drop the new category from the new SiteRDL onto e.g. an element definition or a requirement in the model based on the generic SiteRDL

This drop is shown as allowed, while it should show a "stop" sign, indicating that this is not possible.
The result from this action:
* the hoover text on the item incorrectly includes this new category
* the category tab on the item dialog (inspect or edit) correctly doesn't show this category

There is now a mismatch between the hoovertext and the details dialog. The category cannot be deleted from the UI, will remain visible on the hoovertext, as there is no way to delete it

### Logs

  - [X] There are no logs regarding the issue
 
but relatively easy to reproduce with steps above
  
### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 3.0.3
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [X] Windows OS (32/64 bit): 64-bit
  - [ ] Additional information:

**Comment by MartinFijneman** [comment]
Category incorrectly shown on hoovertext

![Category incorrectly shown on hoovertext](https://user-images.githubusercontent.com/35371313/56814480-94c9eb00-683f-11e9-8938-3324ac50f81e.png)

Category correctly not shown on details tab

![Category correctly not shown on details tab](https://user-images.githubusercontent.com/35371313/56814530-af03c900-683f-11e9-83f2-642cefa1af92.png)

**Comment by samatrhea** [comment]
fix:
  - the drag-over icon needs to be "not allowed" if the dragged category is not in the chain-of-rdls of the target thing
  - no ondrop action if the dragged category is not in the chain-of-rdls of the target thing
 
For those objects that have already been incorrectly categorized there is no easy fix in the GUI. The detailswindows already not load/show categories outside the chain of RDL's. And this we should not revert. So, uncategorizing can only be done using a direct POST message to fix the model. We can also create a built-in rule to check the correctness of used reference data in a model to find `Thing`s where incorrect reference data has been used.

**Comment by samatrhea** [comment]
the following has been implemented:

 - extra check on chain-of-rdls for drag-n-drop operations for Categories and subsequent drop target
 - added drag-n-drop of categories for the following Things: Constant, FileType, Glossary, Option, Parametertype, PossibleFiniteStateList, ReferenceSource (ElementBase and Requirement were already implemented)
  - added right-mouse-click context menu called **Categories** that has as submenu a "remove category" for each of the categories that have been applied to the subject Thing. When clicked the category is removed from the thing

@MartinFijneman @naronatrhea @alexatrhea diff up at D1496
