### ISSUE TITLE
Budget plugin - saving current budget configuration results in empty file 0 kb

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#129]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Budget plugin - saving current budget configuration results in empty file 0 kb
Settings not saved somehow, so not able to (re-)load them.

### Steps to Reproduce

* Open budget browser
* go through settings to create a budget overview
* save configuration

result: saved json file is empty, 0 kb

### Logs

  - [X] There are no logs regarding the issue
  
  
### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 3.1.0.0
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by lxatrhea** [comment]
Looks like saving of Generic budget is taken care of, but for mass budget an error is thrown in the background, saying it is not implemented yet.
