### ISSUE TITLE
Adding ED from model to catalogue gives error if a parameter with a subscription is present

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#13]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

On the demo server, encountered a reproducible problem. In a test performed using the "Quick Test" model (which was very smal, so easy to follow what is happening) and a new catalogue model “Test Catalogue”

problem when using drag-and-drop to copy items between an EM and a catalogue:
* works for ED having parameters without subscriptions
* doesn’t work for ED having parameters with subscriptions
* (in my view) a bit unexpectedly and incorrect, the result of the action depends on whether the data was refreshed or not in the IME:
** it works for an item without any subscriptions
** then in workbook, set a subscription on a paramer within this ED
** try again in the IME to copy to catalogue:
*** it worked for an ED in the IME before performing a refresh
*** it didn’t work anymore for the same ED in the IME after performing a refresh

CDP log files for several of these tests performed are included:
* trying to copy ED containing parameters without subscriptions (all ok)
* trying to copy ED, parameters having subscriptions (error message)
* trying to copy ED with parameter subscription taken in other client (workbook) – (ok before refresh, error message after refresh)
[20180504 CDP4IME - Test for catalogue test - errors seems to occur for EDs with subscriptions.log](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/1984237/20180504.CDP4IME.-.Test.for.catalogue.test.-.errors.seems.to.occur.for.EDs.with.subscriptions.log)
[20180504 CDP4IME - test catalogue including creating with subscription without refresh.log](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/1984238/20180504.CDP4IME.-.test.catalogue.including.creating.with.subscription.without.refresh.log)

### Steps to Reproduce

* create simple model with ED with few parameters for several domains without any subscriptions and empty catalogue
* drag-and-drop from model to catalogue
* add subscription to a parameter
* try again to drag-and-drop from model to catalogue

### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 1.0.8
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [X] Microsoft Excel (32/64 bit): 32
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by samatrhea** [comment]
@MartinFijneman can you check if this still is an issue?

**Comment by MartinFijneman** [comment]
Checked with CDP4 version 1.0.16
Tested on dev server, on model Test Issue 13 and Test Catalogue Issue 13

Now possible to drop element definition in catalogue model if it contains a parameter with a subscription.

Within the catalogue model, the parameter subscription does show an error however, with the following:


Steps performed:
* create test model and catalogue
* add domains SYS, PWR (and THE, but not used further)
* in test model as SYS domain:
** create 2 EDs for SYS
* in catalogue model:
** drag-and-drop items - goes ok
* in test model as PWR domain:
** set subscription on time parameter of SYS in Sys ED 1
** drop item in catalogue
* in test model as SYS domain:
** drop item with subscription from PWR in catalogue

For both these drops with the parameter subscription, the end result is the same, items are created, but with a problem on the value set.
```
[{"classKind":"ParameterSubscription","excludedDomain":[],"excludedPerson":[],"iid":"0905e9ac-7233-4011-85a9-3599c75660fc","modifiedOn":"0001-01-01T00:00:00.000Z","owner":"c52d8b32-6a9c-4ef4-87b6-1e4f97e28e96","revisionNumber":4,"valueSet":[]}]
```

* in test model as PWR and in catalogue model as PWR
** drop item in catalogue - item is not created, 
error message in log file
```
A TwoWay or OneWayToSource binding cannot work on the read-only property 'CopyPermissionDetails' of type 'CDP4CommonView.ViewModels.CopyConfirmationDialogViewModel'.
```

Log file of complete testing sequence:

[CDP4IME - Issue 13.log](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/2287658/CDP4IME.-.Issue.13.log)

**Comment by MartinFijneman** [comment]
testing on public server on 2018-10-31, CDP4 IME gives reproducible crash in case an element definition is moved from catalogue model, in the following case:
* have element definition with parameters of domain X in catalogue model, with subscription on parameter for domain Y
* open up both catalogue and engineering model representing domain Y
* use control + drag-and-drop from catalogue model to engineering model

this for me led to crash, see attached exception report

[20181031 1010 Crash at cntrl and drag-and-drop element definition with subscriptions from CAT-M to EM.txt](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/2535237/20181031.1010.Crash.at.cntrl.and.drag-and-drop.element.definition.with.subscriptions.from.CAT-M.to.EM.txt)
