### ISSUE TITLE
crash occurs when rearranging views within scripting engine browser

### ISSUE THREAD

**Issue by credondorhea** [RHEAGROUP/CDP4-IME-Community-Edition#130]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

rearranging views within scripting engine browser:
picking  up "input" view and trying to change position (goal was to switch "input" and "output" view in this browser

### Logs

 
  - [X] I have attached a log file or included the relevant section in this issue  
  
[CDP4IME - rearranging views within scripting engine browser.log](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/3141939/CDP4IME.-.rearranging.views.within.scripting.engine.browser.log)

[rearranging views within scripting engine browser.txt](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/3141941/rearranging.views.within.scripting.engine.browser.txt)

### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 3.0.3
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by alexatrhea** [comment]
https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues/246

**Comment by lxatrhea** [comment]
> 
> 
> This might be related:
> 
> #246

Unfortunately it's not...

**Comment by lxatrhea** [comment]
Looks like it's a DevExpress bug.
Let's first upgrade DevExpress and then see if it's resolved, or not.

**Comment by samatrhea** [comment]
did some drag and drop, seems to be working fine
