### ISSUE TITLE
Element definitions browser - deleting element definition which is top element leads to crash

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#134]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Element definitions browser - deleting element definition which is top element leads to crash

### Steps to Reproduce

easily reproducible
* create an engineering model
* create an element definition, setting it as top element
* delete the element definition
This leads to a crash of the CDP4 IME

### Logs

  - [X] I have attached a log file or included the relevant section in this issue

windows exception report:
[20190521 1406 delete element definition listed as top element.txt](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/3202433/20190521.1406.delete.element.definition.listed.as.top.element.txt)

CDP4 IME log file:  
[CDP4IME delete element definition listed as top element.log](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/3202430/CDP4IME.delete.element.definition.listed.as.top.element.log)

  
### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 3.1.0.0
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by alexatrhea** [comment]
https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues/52 to fix the missed Iteration cleanup that would have led to this exception.
