### ISSUE TITLE
Element definitions browser - creating EU from ED shouldn't get categories applied directly to EU

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#137]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Element definitions browser - creating EU from ED shouldn't get categories applied directly to EU

Currently when creating an element usage (EU) from an element definition (ED), the EU gets categories applied from the ED instead of being derived from the ED.

As an illustration of the problem, see screenshot, where this leads to a different end-result for 2 EUs, where only the ED has been updated:
* EDs created: top element, and TestElement
* ED TestElement category "EQT"
* create EU and rename to TestElement1
* update ED TestElement by applying other category "Earth Sensors"
* create EU and rename to TestElement2
TestElement1 and TestElement2 as EUs now are different in applied categories overview, see screenshots below

This shouldn't happen. In general, an EU should only show categories as derived from the ED, and any additional category that has been applied to the specific EU directly.

TestElement1 details
![image](https://user-images.githubusercontent.com/35371313/58330758-e2824500-7e37-11e9-8101-d16b68347c78.png)

TestElement2 details
![image](https://user-images.githubusercontent.com/35371313/58330804-fc238c80-7e37-11e9-938d-3284e6f43b18.png)

### Steps to Reproduce

See steps given above

### Logs

  - [X] There are no logs regarding the issue
 
No logs needed, easy to reproduce
  
### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 3.1.1
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by alexatrhea** [comment]
@samatrhea up for review

**Comment by samatrhea** [comment]
@alexatrhea good to land
