### ISSUE TITLE
Number of Elements parameter could be added to Element Usage rather than Element Definition?

### ISSUE THREAD

**Issue by audreyberquand** [RHEAGROUP/CDP4-IME-Community-Edition#138]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Suggestion raised after a student concurrent engineering challenge at Strathclyde University:
The parameter "number of elements" would be more useful as an add-on to an Element Usage rather than an Element Definition. But it's probably defined by the 10-25A Annex A?

### Logs

  - [x] There are no logs regarding the issue
  - [ ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: CDP4-CE version 3.0.3.0
  - [ ] Other:  

- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 

- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [x] Windows OS (32/64 bit): 64
  - [ ] Additional information:

**Comment by samatrhea** [comment]
@audreyberquand Parameters can only be associated (contained) by ElementDefinitions. An ElementUsage then `uses` the defined parameters. But, if one needs to make the value of a Parameter specific for an ElementUsage it is possible to **override** the Parameter for a that ElementUsage.

**Comment by audreyberquand** [comment]
Thanks Sam!

**Comment by samatrhea** [comment]
@audreyberquand are you fine with me closing this issue with the explanation, or do you need more?

**Comment by audreyberquand** [comment]
@samatrhea all ok with closing this issue
