### ISSUE TITLE
Relationship Matrix - filter items on owning domain of extpertise

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#140]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The relationship matrix allows a user to select the kind of thing to show on either vertical or horizontal axis. Filtering on instances can be done using categories. It would be beneficial to be able to filter on a combination of owning domain of expertise (all, a subset. etc.). This filter should only be enabled when the selected kind of thing is an OwnedThing

### Steps to Reproduce
NA

### Logs
NA
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME:  3.1.1

**Comment by MartinFijneman** [comment]
verified

Improvement issue posted separately as #280 

Closing this issue and setting to done
