### ISSUE TITLE
requirements browser - don't flip combo-box for ownership to logged-in domain for existing requirement

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#142]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

requirements browser - don't flip combo-box for ownership to logged-in domain for existing requirement

when a new requirement is created by a user, the combo-box is pre-filled with the domain that the user used to login, this is correct behaviour.

when a participant as a specific domain A is editing an existing requirement that is already assigned to another domain B, the combo-box is switched to the logged-in domain automatically. 
This should not be done, combo-box should show the assigned other domain B correctly.

### Logs

  - [X] There are no logs regarding the issue
 
  
### System Configuration

- CDP4 version:
  - [ ] CDP4-IME: 3.1.1

  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by samatrhea** [comment]
so, basicaly we need to distinguish between the case when an OwnedThing is being edited, or when it is newly created. When it is created, set the DoE to the current logged-in domain, when it is being edited, leave it as is.

**Comment by samatrhea** [comment]
diff up at http://phabricator.rheagroup.com/D1502
