### ISSUE TITLE
requirements browser - editing non-owned requirement shouldn't be allowed for participant with "modify_if_owner" permission

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#143]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

requirements browser - editing non-owned requirement shouldn't be allowed for participant with "modify_if_owner" permission

currently, for a participant with "modify_if_owner" permissions it is possible to select the "edit requirement" menu item on a requirement, opening the "Edit requirement" dialog.

For a participant with "modify_if_owner" permissions, this menu item should be disabled for non-owned requirements.

### Logs

  - [X] There are no logs regarding the issue

  
### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 3.1.1
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by samatrhea** [comment]
seems like an issue with the PermissionService. A issue has been reported on the server that may be related to this https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues/53

**Comment by samatrhea** [comment]
so, now we have to make sure that on the desktop app, the context menu is either disabled or not present when a participant should not have the permission to edit the IOwnedThing (in this case a requirement) in the first place.

**Comment by lxatrhea** [comment]
Found it to be a problem in the SDK:
See https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues/80
