### ISSUE TITLE
RelationshipMatrix: as a user i want to inspect/edit a relationship from the intersection cell of 2 things

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#144]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
A user can create/delete relationships using the relationship matrix. Currently the user cannot inspect or edit the selected relationship from the matrix. This shall be possible

### Steps to Reproduce
 - open relationship matrix and configure in such a way that a relationship is visible.
 - right-mouse click on a relationship -> see that it is only possible to create / delete and not inspect.

### Logs
NA
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 3.1.1

**Comment by samatrhea** [comment]
Add a context menu (one for inspect and one for edit) item for the cell, per existing relationship in that cell. Route it to inspect and edit respectively.

**Comment by MartinFijneman** [comment]
verified, context menu available and working
