### ISSUE TITLE
As a user i want to see the details of a requirement when clicking on the requirement in a properties panel without opening a dialog

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#149]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When a user clicks on a requirement in the requirement tree, that requirement's properties shall be shown on a panel below the trree (in case this properties panel is open). 

### Steps to Reproduce
NA

### Logs
NA
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 4.0.0

**Comment by samatrhea** [comment]
see the relationship browser for an example on how to split the information in the view with a view that can be collapsed

**Comment by alexatrhea** [comment]
Implementation. Notice circled panel toggle button. This, just as with the favoriting, has been made in such a way that it could be reused in other panels.

![image](https://user-images.githubusercontent.com/22167021/73081083-42e5ec80-3ec7-11ea-80ef-64b6a464a93a.png)

**Comment by mmilitaru** [comment]
Hiding/Showing button has been removed since the panel is collapsible
