### ISSUE TITLE
Problem with execution of copying item from catalogue model to Marco Polo engineering model

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#15]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

situation:
on the demo server:
in earlier step, setup a catalogue model for power domain, with a base equipment, worked ok to add items to Marco Polo model on (added 3 items as needed).
set up a catalogue model for structures domain, with a base equipment

for this catalogue, trying to drag-and-drop from the catalogue to the Marco Polo model gives an error message “task cancelled” after some time.

Note that I initially put subscriptions on several parameters (no compound parameters present in the catalogue) for the system domain (on mass, mass margin, nr of equipment and on a few items within a parameter group “risk”, TRL and heritage details).

After failing to create a new item (issue on github already available for this), tried again after removing the subscriptions. This didn’t help, still not able to create a ED in the Marco Polo model from the catalogue, now for parameters without any subscriptions.

Log file attached with logs from 2 specific actions:
* log in, open models (Marco Polo, catalogue) as STR domain
* open ED browsers, and drag ED “new equipment” from catalogue to marco polo browser
### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 1.0.10 (intermediate version)
[20180514 1215 CDP4IME - Copy ED from catalogue STR to Marco Polo model.log](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/2012766/20180514.1215.CDP4IME.-.Copy.ED.from.catalogue.STR.to.Marco.Polo.model.log)

  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by samatrhea** [comment]
cannot reproduce
