### ISSUE TITLE
As a User I want to have better access to the requirement definition from the relationship matrix screen

### ISSUE THREAD

**Issue by MSamoil** [RHEAGROUP/CDP4-IME-Community-Edition#159]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [ ] CDP4-IME: 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by samatrhea** [comment]
see https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues/150 

When a user clicks on a thing (column or row) in the RelationshipMatrix, that Thing's properties shall be shown on a panel below the trree (in case this properties panel is open). Typical use-case is to show the defenition of a requirement

**Comment by samatrhea** [comment]
Investigate up to how much this is already implemented. I think row definition already works.

**Comment by alexatrhea** [comment]
1. Column thing tooltip not displayed when cell selected.

2. Make tooltip textboxes same (constant) size/scrollable.

**Comment by MartinFijneman** [comment]
verified, inspect and edit on rows and columns working
