### ISSUE TITLE
Excel plugin not working when installing within Parallels VM

### ISSUE THREAD

**Issue by KarstenB** [RHEAGROUP/CDP4-IME-Community-Edition#16]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
We just installed CDP4 on a bunch of computers, and on all except two the Excel Addin appeared and worked. However on the MacBooks, which are running parallels VM, the addin does not work (show up). 

### Steps to Reproduce
Install CDP4 in a windows 10 parallels VM on a Macbook

### System Configuration

- CDP4 version:
  - [x] CDP4-IME: CDP4IME-CE-1.0.8.x64
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [x] Microsoft Excel (32/64 bit): task manager shows it as 32 bit running
  - [x] Windows OS (32/64 bit): 64
  - [ ] Additional information: 

I checked issue #4 and the registry in question is not created, while the files are installed as expected. So I created a little reg file, which does make it visible in the COM Addin section of the Excel Settings-Options-panel. But excel fails to activate it, and it also does not show a path to the dll. It appears the Addin dlls didn't get registered.

**Comment by samatrhea** [comment]
Hi,

In the release notes of version [1.0.7](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/releases/tag/1.0.7) we state the following:

>  When you are using 64-bit excel you need the 64-bit installer. If you are using 32-bit excel, even on a 64-bit windows, you need the 32-bit installer.

This seems like a documentation issue and most likely we need to improve the installer to make sure this problem does not occur and users are informed. Can you let us know whether the problems are solved when installing the 32-bit version in combination with 32-bit excel? And, can you let us know what version of excel you are using (2010, 2030, 2016, etc)? To find out what bitness of excel you have installed navigate to _File -> Account -> About Excel_, a window like this should pop-up

![image](https://user-images.githubusercontent.com/22165725/40264708-bb6159ba-5b2a-11e8-8618-8b2c61e6f5f3.png)

**Comment by samatrhea** [comment]
@KarstenB any update on this issue?

**Comment by KarstenB** [comment]
Hey, I was able to resolve the issue on my laptop by installing the 32 bit version, and by uninstalling the older .5 and replace it with a newer .8 64 bit version on my colleagues laptop.

**Comment by KarstenB** [comment]
As everything works now, this issue can be closed.
