### ISSUE TITLE
RelationshipMatrix: when a configuration is loaded, the matrix is not redrawn

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#162]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When a configuration is loaded, the matrix is not redrawn immediately. A user can trigger a redraw when clicking on the "flip axis" button. When a config is loaded, the redraw should be triggered immediately.

### Steps to Reproduce
  - load a config
  - see that matrix is not populated
  - click on the flip button and see that matrix is populated

### Logs
NA
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 4.0.1

**Comment by MartinFijneman** [comment]
As discussed: redraw when changing configuration should also include resetting the matrix, i.e. from a loaded configuration being able to go back to starting point (i.e. all fields and the matrix itself empty).
