### ISSUE TITLE
Clear indication or identification of deprecated items across views, dialogs, dropdowns etc. needed

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#165]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Clear indication or identification of deprecated items across views, dialogs, dropdowns etc. needed

Various items can be set to "deprecated". Often a user wants to do this to correct an error, e.g. accidentally adding an item twice. The item can be set to deprecated, and is then filtered out in its main view (e.g. list of domains of expertise)
For this item being used in other views, the deprecated item sometimes show up in other views, where this information is being used. It is then not possible from that specific view/dialog/ dropdown etc. to see which was is e.g. the active and "correct" item, and which one is the deprecated one.

An example of this is the list of domains of expertise in the Engineering models browser. Deprecated domains are given in the same format, font and colour as the un-deprecated items. If you have identical items (e.g. for these accidental duplicates that you wanted to clean up by setting one to deprecated), it is impossible from this view to distinguish.

A clear indication that is then applied across the whole application as far as possible would be beneficial for these kind of cases.
As a suggestion, change font colour and background of deprecated items to grey, as is done already in the RDL browsers. This could be extended to other views. For dropdowns and selection lists, in any case also a grey font colour could be used.

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 4.0.1
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by alexatrhea** [comment]
This is fixed in https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/pull/247
