### ISSUE TITLE
Bug Report: Miss-matching in the Relationship Matrix when switching axis

### ISSUE THREAD

**Issue by credondorhea** [RHEAGROUP/CDP4-IME-Community-Edition#168]
### Prerequisites

- [X ] I have written a descriptive issue title
- [X ] I have verified that I am running the latest version of the CDP4-IME
- [X ] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When displaying a relationship between X-Axis and Y-Axis categories in the relationship matrix, if you switch the axis, the elements on the Y-axis miss-match (when inspecting "row thing", the short-name displayed on the Y-axis does not match the description of the requirement. This does not happen if instead of displaying the short name, I display the complete name).

### Steps to Reproduce
Create a relationship between 2 elements in the relationship matrix. (in this example, they were both requirements).
Switch Axis.
Select short names to appear.
Inspect row thing: the description of the requirement does not match the short name displayed on the Y-axis.

### Logs

  - [X ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [ X] CDP4-IME: 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by credondorhea** [comment]
![2](https://user-images.githubusercontent.com/50144749/60507048-8c6eb000-9cc7-11e9-85c1-8024b3618f7a.PNG)

This file represents the problem:
Y-Axis element refers to MIS-040, while in fact the Requirement is TC-030 (as seen in the inspect thing window).

**Comment by alexatrhea** [comment]
Becoming quite relevant. I think the issue is somehow in virtualization of the grid.
