### ISSUE TITLE
The export feature can duplicate objects

### ISSUE THREAD

**Issue by naron-rhea** [RHEAGROUP/CDP4-IME-Community-Edition#17]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When exporting data from the expert session feature from the test-server the object Person "John Doe" was duplicated in the SiteDirectory json file.

### Steps to Reproduce
- log into the test-server
- open a model
- export the session

### Logs
  - [x] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 
  - [ ] Other: 
  -
- Web Services:
  - [x] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by samatrhea** [comment]
fixed by upgrading to CDP4-SDK version 1.4.0 https://github.com/RHEAGROUP/CDP4-SDK-Community-Edition/issues/21 in 3f42952da7936546bf45897bdd2ed137aa3b8c04
