### ISSUE TITLE
Select iterations to open-dialog: review implementation for ordering and prefilling

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#176]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

opening a model, in the current implementation of the dialog "Select iterations to open", the list of iterations doesn't seem to be ordered. A reviewed implementation is requested for this dialog, with following properties:
* on opening, show engineering models collapsed for their contained iterations
* expanding to show the iterations, apply sorting to iterations:
** by creation date of iteration
** newest active iteration on top
** prefill the selection box with default domain if participant is assigned to that domain within the model

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/35371313/61055744-70b78800-a3f2-11e9-9dec-8f974c69ede0.png)

### Logs

  - [X] There are no logs regarding the issue
   
  
### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 4.0.2
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by samatrhea** [comment]
The open model dialog has been refactored already (in a different manner than requested here). This is can be closed.
