### ISSUE TITLE
Opening Publication panel fails after creation of Option dependent parameter and providing values.

### ISSUE THREAD

**Issue by alexatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#178]
### Prerequisites

After creating a few option dependent parameters and deleting some others there was an error loading the publication panel:

![image](https://user-images.githubusercontent.com/22167021/61381073-6853c700-a8a2-11e9-88c7-b3ca858abdac.png)

There might be a model problem arising further from this (breaking the model).

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Logs

  - [ ] There are no logs regarding the issue
  - [ ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by mmilitaru** [comment]
I cannot re-produce. I found another issue though, which I will create another issue.

**Comment by alexatrhea** [comment]
Ok. Moving to "Manual Test Required" for @MartinFijneman to verify.

**Comment by samatrhea** [comment]
i have also tried to reproduce, i cannot get an error to occur.
