### ISSUE TITLE
External display of categories in the Relationship Matrix does not follow alphabetic order.

### ISSUE THREAD

**Issue by credondorhea** [RHEAGROUP/CDP4-IME-Community-Edition#183]
### Prerequisites

- [ X] I have written a descriptive issue title
- [X ] I have verified that I am running the latest version of the CDP4-IME
- [ X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The external display of categories in the Relationship Matrix does not follow an alphabetic order, which is followed inside the category selector checkbox.

### Steps to Reproduce
Select multiple same categories for both X and Y Axis, see the category that is displayed from the outside of the combo box does not correspond with the one that alphabetically should be. In the file attached, the same categories have been selected for both axis, but in the X-Axis the one displayed from the outside is "Mission Analysis Descriptor", and in the Y-Axis "Communications Descriptor", but if following the order they appear in the checkbox, the first one for both X and Y-Axis should be "AOGNC Descriptor".

This can lead to a misunderstanding, in the example, that in the X-Axis "Communications Descriptor" has not been selected since the one that appears from the outside is Mission Analysis, which would come later in the alphabet.

### Logs

  - [X ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [X
![Capture](https://user-images.githubusercontent.com/50144749/62626383-90759980-b927-11e9-94a5-266ed09035f8.PNG)
 ] CDP4-IME: 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by MartinFijneman** [comment]
verified: alphabetic ordering in categories
