### ISSUE TITLE
Requirements - add possibility to export to spreadsheet

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#188]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Include possibility to export a requirements specification to spreadsheet. To start, can be an export of the (almost) full specification, so:
* specification
* groups
* requirements
These could be exported with the following columns:
* Shortname
* Name
* Definition
* Owner

For the requirements themselves, then requested to provide the following associated information:
* categories (single column with all applied categories, using separators)
* simple parameter values (multiple columns)
** shortname
** name
** value
** scale (if applicable)
* parametric constraints (multiple columns)
** [TBD: logical expression]
** parameter type
** scale
** operator
** value

### Logs

  - [X] There are no logs regarding the issue
  - [ ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 4.0.3 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by samatrhea** [comment]
diff up at D1519

**Comment by samatrhea** [comment]
@MartinFijneman I have not implemented ParameterTric constraints in this export. For each requirement there can be rather complex boolean expressions. I am not convinced this is easily captured in a column in excel. I propose that if this is a hard requirement for this sheet we add a new issue to add this information to the exported sheet.

**Comment by MartinFijneman** [comment]
requirements export checked, is working as described and as expected:
* requirement specification
* requirement group
* requirement: short name, name, description, owner, category
* simple parameter values (if existing)

A separate issue has been created: 
* for the parametric constraint: #260 
* for the sorting of requirements:  #261

Closing this one
