### ISSUE TITLE
Update solution to make use of reqifsharp version 2.0.0

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#200]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Newer versions of reqifsharp have been published on nuget.org. The purpose of this issue is to update to at least version 2.0.0 and verify that import/export keep working as expected.

### Steps to Reproduce
NA

### Logs
NA
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 4.0.4

**Comment by mmilitaru** [comment]
#200 ReqIf is already the latest version 2.0.0.
