### ISSUE TITLE
If panel with deprecated items is opened while "show deprecated" is already turned on in Ribbon, the rows are still hidden.

### ISSUE THREAD

**Issue by lxatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#201]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
If a panel with deprecated items is opened while "show deprecated" is turned on in Ribbon, the rows are still hidden.

### Steps to Reproduce
- Open "Parameter types"panel
- Set a parameter type as "Deprecated" 
- Close "Parameter types" panel
- Set the "Show Deprecated Things" menu option "on"
- Open "Parameter types" panel again
The deprecated thing is not visible now.
When you toggle the "Show Deprecated Things" menu option twice ("off" and "on" again) they do show.

### Logs
NA
  - [x] There are no logs regarding the issue
  - [ ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration
NA

- CDP4 version:
  - [ ] CDP4-IME: NA
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: NA
  - [ ] OCDT WSP version: NA
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): NA
  - [ ] Windows OS (32/64 bit): NA
  - [ ] Additional information: NA

**Comment by alexatrhea** [comment]
this was already fixed
