### ISSUE TITLE
Improve parametric constraint display in requirements tree and fix reaction to model changes.

### ISSUE THREAD

**Issue by lxatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#216]
Bug: Parametric constraint rows don't update on model changes.

Improvement: Make Parametric Constraint display of information consistent with SimpleParameterValue rows and improve readability.

Part of #182

**Comment by lxatrhea** [comment]
@alexatrhea Could you take a look?

**Comment by MartinFijneman** [comment]
verified, implementation change clear for me
