### ISSUE TITLE
Implement drag-and-drop from ElementDefinition and ProductTree to parametric constraints in Requirement Browser and vice versa.

### ISSUE THREAD

**Issue by lxatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#217]
When a parameter is dragged from a ProductTree or ElemenDefinition tree onto an expression in an Parametric Constraint in the RequirementsBrowser, it should create a relationship between the parameter and the constraint.

Dragging an expression to a parameter should do the same.

If relationship exists between the two, the icons shall indicate that a link on a particular thing exists.
A RelationalExpression can have [0..1] relationship.
A Parameter can have [0..*] relationship.

There shall be a context menu that provides functionality to remove the relationship.

Part of #182

**Comment by lxatrhea** [comment]
@alexatrhea: could you take a look at this at this location:
https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/compare/requirementbrowser_parametricconstraint_display_improvements

**Comment by MartinFijneman** [comment]
verified, link is being created.
