### ISSUE TITLE
DalWriteException while creating a Finite States

### ISSUE THREAD

**Issue by oiynick** [RHEAGROUP/CDP4-IME-Community-Edition#22]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Possible finite state DalWriteException: "Sequence contains more than one element" during Possible Finite States List creating

### Steps to Reproduce
Open a model, open an iteration, start creating possible finite states list and possible finite states, hit "OK"

### Logs

  - [ ] There are no logs regarding the issue
  - [x] I have attached a log file or included the relevant section in this issue  
 
 [Untitled.xlsx](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/2118491/Untitled.xlsx)

### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 1.0.13 
  - [x] Other: The bug has also been there on 1.0.7 and 1.0.8 CDP4-IME versions
  
- Web Services:
  - [x] CDP4 Web Services version: 1.0.1
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit):
  - [x] Windows OS (32/64 bit): Windows 10 Pro 64
  - [x] Additional information: Mac Windows BootCamp Machine

**Comment by samatrhea** [comment]
this has been fixed in new release of CDP4 Web Services. It is recommended to update to at least verion 1.0.8 of the services
