### ISSUE TITLE
Disable creation of more than Option from the GUI when the model is a catalogue

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#223]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When a model is a catalogue a user is allowed from the GUI to create a new Option. The server already does not allow it anymore and returns an exception (as it should). The GUI should not allow it either.

### Logs
NA

### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 4.0.4

**Comment by MartinFijneman** [comment]
context menu item is greyed out

verified

Setting to done
