### ISSUE TITLE
ElementDefinition browser missing icons on Option and State dependent value set rows.

### ISSUE THREAD

**Issue by alexatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#225]
Option and State dependent rows do not show icons in the element definition browser (and potentially Product Tree).

**Comment by samatrhea** [comment]
i have verified that both option dependent and state dependent parameters in the ElementDefinition Browser now show the required icons

**Comment by MartinFijneman** [comment]
icons visible, verified
