### ISSUE TITLE
Team Composition process available for the closed session

### ISSUE THREAD

**Issue by oiynick** [RHEAGROUP/CDP4-IME-Community-Edition#23]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The team composition window can be opened for a closed session: the previous member session still available for the Team Composition process 
![teamcomposition](https://user-images.githubusercontent.com/36442331/41648448-33bce106-7479-11e8-9cd9-7cce6e66f7a7.PNG) since the session is closed 
![disconnectoptions](https://user-images.githubusercontent.com/36442331/41648459-3d902cd8-7479-11e8-842d-6fa89aeda4a4.PNG).

### Steps to Reproduce
Open a session for user, open another session for another user, close disconnect from the first session, hit "Team Composition" button.

### Logs

  - [x] There are no logs regarding the issue
  - [ ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 1.0.13 
  - [ ] Other: The bug has also been there on 1.0.7 and 1.0.8 CDP4-IME versions.
  
- Web Services:
  - [x] CDP4 Web Services version: 1.0.1
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [x] Windows OS (32/64 bit): Windows 10 Pro, x64
  - [x] Additional information: Mac Windows BootCamp Machine

**Comment by mmilitaru** [comment]
The issues can be reproduced even for one session. Upon closing, the session still shows in Team Composition sub-menu.

**Comment by MartinFijneman** [comment]
tested with both single and multiple users: team composition browser is closed, info no longer available, as expected.
