### ISSUE TITLE
Improve Relationship link  icon overlay.

### ISSUE THREAD

**Issue by alexatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#231]
The current relationship link icon overlay is not very good with light icons. Contrast is not controlled. Examples of bad combination: RelationalExpression.

**Comment by alexatrhea** [comment]
I am open to ideas here. I have tried various things but it seems like due to the extremely low resolution of the overlay (8x8px) on a 16x16 icon, it is very hard to have this be contrasting enough in all cases.

One of the things I thought about is to think a bit differently and when a Thing gets related, show the link icon as the main 16x16 icon and the Thing icon as the small overlay. This way I think the related things will stand out way more than now among the other unrelated Things. Thoughts?

@samatrhea @lxatrhea

**Comment by lxatrhea** [comment]
@alexatrhea @samatrhea 
Another idea: Use a separate (2nd) icon right next to the current icon. 
Show whitespace, or a very light gray icon when there aren't any relations and use a colored one (green? black?) if there are. 
Maybe make it a bit smaller (12x12?). 
Add a specific tooltip?

**Comment by alexatrhea** [comment]
I like this idea even better and I think we can try, but overall I think this needs to be done with updates to converter and not through addition of extra XAML or icons, performance-wise and number of changes wise this will be A LOT better.

**Comment by lxatrhea** [comment]
Problem is that all icons concerned are set to be 16x16 pixels in XAML. 
So no matter what we do in ThingToIconConverter, the icon is always shown in 16x16 pixels.

@alexatrhea @samatrhea What to do now...

**Comment by alexatrhea** [comment]
we table this for now until we can do a 10 minute all in the same room together at some point.
