### ISSUE TITLE
export to reqif fails

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#237]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When trying to export the requirements from a model to a ReqIF file, the export fails. The requirements set in question contains:
  - Requirements Specification
  - Requirement Groups
  - Requirements
  - SimpleParameterValues

### Steps to Reproduce
Open a model that contains requirements and notice that it fails.

### Logs
NA
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 4.0.4

**Comment by alexatrhea** [comment]
Followup in #255 .

**Comment by MartinFijneman** [comment]
reqIF export not verified: for 2 tests (one on DEV with testing model, one on AMCDF with testing model), got error messages ("String was not recognized as a valid Boolean." or "The string 18/12/2019 09:05:06 cannot be parsed to a DateTime")

**Comment by MartinFijneman** [comment]
issue reported when reopening perpaphs due to #266 and #268 ?

**Comment by alexatrhea** [comment]
I think this is a different issue than the root of this one. I still close this, and will take care of it in #255 , from your reports it seems like date time handling is broken all over the place.
