### ISSUE TITLE
As a user I want to visualize how a value of a parameter has changed over time

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#243]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Based on CDP3 feature: allow a user to select one or more parameters for which a graph is presented that shows how the value of this parameter(s) changes over time -> "track parameter", 

The graph needs to have the following features:
  - show data points per iteration and/or per change
  - show per data-point which person made the change (who did what when) -> this can be done using some form of labels (that can be enabled/disabled), or by allowing the user to select a data point and get more information in a details panel -> text box
  - since a parameter has potentially multiple valuesets a decision has to be made how this can be achieved, meaning: option dependency and statefullness needs to be taken into account in the design of the GUI

### Steps to Reproduce
NA

### Logs
NA
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 4.0.4

**Comment by MartinFijneman** [comment]
initial implementation working quite nicely.

Follow-up items reported as separate new issues:
#366 
#367 
#368

**Comment by MartinFijneman** [comment]
verified current implementation, closing this issue
