### ISSUE TITLE
Improve Parametrized Category Rule dialog

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#245]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The Parametrized Category Rule dialog allows a user to select multiple parametertypes that are _part_ of the rule. The horizontal spacing of the grid does not cover complete dialog, should span (closer) to the edge

![image](https://user-images.githubusercontent.com/22165725/70850906-a07e2680-1e8f-11ea-83ae-61833a6fd42c.png)

### Steps to Reproduce
Create new rule and observer described behavior

### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 4.0.4

**Comment by MartinFijneman** [comment]
sizing ok

verified

Closing this issue and setting to done
