### ISSUE TITLE
Roles browser: disable inline edit.

### ISSUE THREAD

**Issue by alexatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#250]
The inline edit of permissions in the Roles browser should be disabled. As it is now it is too prone to unintentional edits by simple misclicks or mousescrolls, potentially irreperably editing the permissions, as the changes are immediately sent to the server.

Suggest to only leave it editable in the dialog, to make the process:

1. Intentional
2. Safe. By not having it POSTed to the serviecs straight away, you give the user the ability to correct mistakes before too late.

**Comment by samatrhea** [comment]
sounds reasonable to me

**Comment by mmilitaru** [comment]
The whole combo column will be replaced by a text and a header caption will be added.
