### ISSUE TITLE
Expand and Collapse context menu options appear in grids with no expandable or collapsible rows.

### ISSUE THREAD

**Issue by alexatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#254]
Expand and Collapse context menu options appear in grids with no expandable or collapsible rows.

BrowserViewModelBase@872

_Originally posted by @lxatrhea in https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/pull/247_

**Comment by MartinFijneman** [comment]
while testing, noticed related issues, posted as separate new issue #279 

for this issue, verified, context menu item not appearing in grids, therefore close and move this issue to done
