### ISSUE TITLE
Excel Requirements export to spreadsheet - remove deprecated requirements from export

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#258]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Related to #188 testing, opened new issue:

all requirements are included in the export currently, including those set to deprecated. Suggested improvement for this, for now I see 2 options:
1) include deprecated items, but show with different markup in the exported file (grey text and background). Advantage is of having the complete set of requirements. Adding a "deprecated" column would allow to more easily filter these out.
2) don't include the deprecated items. Is simpler and more correct for most purposes (foreseen/intended usage)

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 5.0.0 RC 1
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by samatrhea** [comment]
@MartinFijneman I made the decision to filter deprecated requirements out of the generated speadsheet. We can always provide a user with the possibility to configure the export with a detailed configuration settings window. This should be something for a dedicated issue. Potentially these settings can also be used to configure a ReqIF export

**Comment by MartinFijneman** [comment]
verified

Setting to done
