### ISSUE TITLE
Requirements browser, edit to create simple parameter values - implement allowed values formatting

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#259]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Requirements browser, edit to create simple parameter values - implement allowed values formatting

Currently for the dialog for editing a simple parameter value for a requirement, the value box is not checked according to the allowed formatting for the following types:
* date
* datetime
* time of day

This is now a free field, which leads to inconsistencies in the data.

Proposed to implement the same selection mechanisms (using the calendar and time bars to pick the required date/time)

### Steps to Reproduce

Create requirements specification, requirement, and then add simple parameter values of types date, datetime and time of day.

### Logs

  - [X] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 5.0.0 RC 1
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by MartinFijneman** [comment]
potentially fixed already, needs manual testing to verify

**Comment by MartinFijneman** [comment]
further testing needed, in any case date parameter type not handled correctly. See #266 for same problem for parametric constraints.

All types need to be checked for both simple parameters and parametric constraints

**Comment by MartinFijneman** [comment]
reopening: issue for enumeration parameter type - using value name or short name leads to problem if this is different (e.g. using spaces in name and not in short name)

e.g.: enumeration parameter type solar array, has values:
name | short name
wing | wing
body mounted | body_mounted

For this, it is not possible to set the value in a relational expression

![image](https://user-images.githubusercontent.com/35371313/72275313-f7615200-362d-11ea-9062-58a95968fc20.png)

**Comment by MartinFijneman** [comment]
handling of value for time of day parameter type seems done correct for simple parameter value, but not correct in parametric constraint - time is turned into date-time

![image](https://user-images.githubusercontent.com/35371313/72276102-7acf7300-362f-11ea-94c5-8821528f606f.png)

**Comment by lxatrhea** [comment]
Allready solved in pull request #283 for issue #266.
