### ISSUE TITLE
publication mechanism - excel crash when creating publication from non-updated WB with older value

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#263]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

publication mechanism - excel crash when creating publication from non-updated WB with older value

excel crashes when trying to create a publication for a parameter that has been published, and updated again, if this publication attempt is done from WB that has not been updated, see steps to reproduce

### Steps to Reproduce

* open model in IME (Client A) and in Workbook (client B), and open publication browser in both
* WB client B is not updating, client A IME has refresh on
* change value of a parameter, making this publishable (from either client), making sure this is visible in both client A and B
* create publication in client A IME
* from client A IME, change parameter value again, and create 2nd publication
* from client B WB, try to create publication for the non-updated 1st parameter change
This leads to a crash of excel.

Please note that this only happens if the value of the parameter has been updated and published. For earlier tests, doing the same multiple client (A,B) publication on the same value change leads to the creation of 2 publications.

### Logs

  - [ ] There are no logs regarding the issue
  - [X] I have attached a log file or included the relevant section in this issue  
  
[20191218 1758 CDP4IME - Excel crash when creating publication from WB for already published parameter.log](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/3979582/20191218.1758.CDP4IME.-.Excel.crash.when.creating.publication.from.WB.for.already.published.parameter.log)

### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 5.0.0 RC 1
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by lxatrhea** [comment]
I am unable to reproduce this. 
I tried several times, but no Excel crash here.

@MartinFijneman Please try this using the latest versions of IME and WebService and see if the problem is still there.

**Comment by MartinFijneman** [comment]
on version 5.0.2 not reproducible

@samatrhea tbd if the behaviour is as wanted: testing with creating a publication from a workbook that was not updated (with several changes with publications in between from another client), the publication is created, but the value doesn't seem to be taken - the value that is present in the workbook after a rebuild is from the latest change in another client (in this case IME)

**Comment by samatrhea** [comment]
@MartinFijneman not sure i fully understand what you mean, i think it's best that we sit together and you show me what is going on. Then we can figure out what the behavior should be.

**Comment by samatrhea** [comment]
In order to reproduce this follow these steps: 
  - using IME: Create a model that has 1 ED with at least one Parameter per ParameterType (boolean, date, datetime, etc.), set autorefresh to true.
  - rebuild a workbook for the owner domain of expertise
  - for each parameter create a cell on a calculation sheet with a cell-name (convention is to start the cellname with "LINK_")
  - use the cellname stated on the calc sheet in the "computed" value of each corresponding parameter
  - set the switch to COMPUTED so that the actual value is that of the values coming from the calc sheet
  - submit these changes to server 
  - in IME wait for new data to arrive
  - publish parameters -> now the crash should occor

In further discussion with @MartinFijneman it seems the computed value may be causing the problem

**Comment by alexatrhea** [comment]
We need to review if this is still open. @alexatrhea

**Comment by alexatrhea** [comment]
Do one more confirmation that this is fixed and if so, close indiscriminately. Any further information from @MartinFijneman shall be in a new ticket.

**Comment by lxatrhea** [comment]
What happened was that I erroneously closed the issue.
When I reopened, the issue was automatically moved back to the backlog, while it had to stay in "Manual Test Required".
Tested the repro scenario of 31 january. Looks OK now.

**Comment by alexatrhea** [comment]
perfect
