### ISSUE TITLE
Date parametric constraint in the requirement browser - value wrongly represented as datetime

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#266]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

For date parameter type used as parametric constraint in the requirement browser, the representation is wrong in the browser and in the edit dialog. The selection is correctly as a date, the representation in thee views is incorrectly as datetime.

![image](https://user-images.githubusercontent.com/35371313/71270239-67432c00-2351-11ea-9549-2866a0a81665.png)

### Steps to Reproduce

create requirement, add parametric constraint with date parameter type, and provide value.

### Logs

  - [X] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 5.0.0 RC2
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by lxatrhea** [comment]
It is not entirely clear to me how things work at the moment and how this should work.
For sure there are differences!

@samatrhea @alexatrhea
We should review the dataflow and conversions for Date/Datetime/TimeOfDay ParameterTypes from Client to Server to database and vice versa.

**Comment by samatrhea** [comment]
@lxatrhea agreed, lets do that early next week.
