### ISSUE TITLE
Parametric Constraint's last relational expression must not be removed

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#267]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

remove parametric constraint if only or last relational expression is removed

Currently, when removing (a) relation expression(s), the parametric constraint remains as empty placeholder. It would be better to remove the parent parametric constraint when it only has 1 relation expression and this is being removed.

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 5.0.0 RC2
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by lxatrhea** [comment]
@MartinFijneman 

This would be the 3rd way of handling the deletion of child things in the Requirement system:
1) In the ParametricConstraint editor it seems like you can't delete the last RelationalExpression

2) When the last RelationalExpression is deleted from a parent BooleanExpression (AND, OR, etc) the parent BooleanExpression shows an error overlay.

3) Now you want an automatic delete action for the parent Parametric constraint.

Could we standardize the way we implement this?

**Comment by samatrhea** [comment]
@lxatrhea and @MartinFijneman, 10-25 dictates the following:

```
ParametricConstraint.expression | BooleanExpression [1..*] {composite}
```
so, there needs to be at least one BooleanExpression in a ParametricConstraint. 

We shall not allow a user to delete the last `BooleanExpression`, this needs to be enforced by both the UI and the server. If the intention of the user is to delete the ParametricConstraint, (s)he should do just that,
