### ISSUE TITLE
The FilterStringService registers IDeprecatableToggleViewModel which is not available in the addin, none of the views that have deprecated things in them are now available in the Add-In

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#271]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Trying to load a view in excel that contains deprectad things (requirements, reference data etc.) no longer works as the `FilterStringService` depends on `IDeprecatableToggleViewModel` which is not available in the Add-In

### Steps to Reproduce
  - open excel
  - connect to a data source and open a model
  - open the `ParameterTypes` or the `Requirements` and notice that the panel does not load.

### Logs
NA
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 5.0.1

**Comment by MartinFijneman** [comment]
verified

Setting to done

**Comment by MartinFijneman** [comment]
IME still broken, pending merge of https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/pull/275
