### ISSUE TITLE
Common / Domain File Store Functions do not work properely

### ISSUE THREAD

**Issue by stepjah** [RHEAGROUP/CDP4-IME-Community-Edition#276]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The File Store Functions (Common & Domain) do not seem to be working. It is not possible to create File Stores or to upload files. When trying to create a file store / folder, system exceptions are thrown and no dialogue is shown. When trying to upload a file, a "Save as file..." dialogue pops up instead of an "Open file" dialogue which you would normally expect. After selecting a file, the user is asked if this local file shall be overwritten, which is not what the user wants. No file shows up in the CDP4 files stores. 

### Steps to Reproduce
Open any Engineering Model and Open the Common / Domain File Store views. Click on create an item. Click on "Create a Common File Store / a Folder" --> Exception
Click on "Upload a File to the File Store" --> unexplainable behaviour and wrong dialogue

### Logs

> 01.03.2020 11:09	CDP4EngineeringModel.ViewModels.CommonFileStoreBrowserViewModel	Error	"System.Exception: An IThingDialogView for CommonFileStore has not been registered with the Application
>    bei CDP4Composition.Navigation.ThingDialogNavigationService.ResolveViewType(ClassKind classKind)
>    bei CDP4Composition.Navigation.ThingDialogNavigationService.Navigate(Thing thing, IThingTransaction transaction, ISession session, Boolean isRoot, ThingDialogKind dialogKind, IThingDialogNavigationService thingDialogNavigationService, Thing container, IEnumerable`1 chainOfContainers)
>    bei CDP4Composition.Mvvm.BrowserViewModelBase`1.ExecuteCreateCommand(Thing thing, Thing container)"
> 01.03.2020 11:10	CDP4EngineeringModel.ViewModels.DomainFileStoreBrowserViewModel	Error	"System.Exception: An IThingDialogView for Folder has not been registered with the Application
>    bei CDP4Composition.Navigation.ThingDialogNavigationService.ResolveViewType(ClassKind classKind)
>    bei CDP4Composition.Navigation.ThingDialogNavigationService.Navigate(Thing thing, IThingTransaction transaction, ISession session, Boolean isRoot, ThingDialogKind dialogKind, IThingDialogNavigationService thingDialogNavigationService, Thing container, IEnumerable`1 chainOfContainers)
>    bei CDP4Composition.Mvvm.BrowserViewModelBase`1.ExecuteCreateCommand(Thing thing, Thing container)"

  - [ ] There are no logs regarding the issue
  - [x] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 4.0.3.0
  - [ ] Other: 
  -
- Web Services:
  - [x] CDP4 Web Services version: 4.0.0 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [x] Windows OS (32/64 bit): WIN10, 64 bit
  - [ ] Additional information:

**Comment by alexatrhea** [comment]
Part 2 will be handled in separate followup tickets.
