### ISSUE TITLE
Expand and Collapse context menu options not available or not working for specific items

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#279]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

While testing #254 noticed expand/collapse menu item either missing or not working for the following browsers;

No expand or collapse items present on:
=======================================

Engineering models browser:
* participants
* iterations
* active domains

Element Definitions browser:
* Element Usage

CDP4 Object Browser
* not available on all items/ levels

Person roles browser:
* person role (folder item)
* participant role (folder item)

Finite States browser:
* Possible Finite State List (folder item)
* Actual Finite State List (folder item)

Relationships browser:
* Binary Relationships (folder item)
* Multi Relationships (folder item)

Publications browser
* domain row with parameters to be published

Requirements browser:
* Parametric Constraints (folder item)
* Simple Parameter Values (folder item)

Menu item available, but not working on:
========================================

Organizations browser
* organization

Rule Verification lists browser
* Rule verification list

### Logs

  - [X] There are no logs regarding the issue
  - [ ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 5.0.2 RC
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by mmilitaru** [comment]
After discussion with @alexatrhea we have decided that Object Browser will not be fixed within this issue because it requires more refactoring.

**Comment by MartinFijneman** [comment]
Checked for:

Engineering models browser:

[]    participants
[]   iterations
[]    active domains

Element Definitions browser:

[]    Element Usage

CDP4 Object Browser

[]    not available on all items/ levels

Person roles browser:

[]    person role (folder item)
[]    participant role (folder item)

Finite States browser:

[]    Possible Finite State List (folder item)
[]    Actual Finite State List (folder item)

Relationships browser:

[]    Binary Relationships (folder item)
[]    Multi Relationships (folder item)

Publications browser

[]    domain row with parameters to be published

Requirements browser:

[]    Parametric Constraints (folder item)
[]    Simple Parameter Values (folder item)

Organizations browser

[]    organization

Rule Verification lists browser

[]    Rule verification list

**Comment by MartinFijneman** [comment]
tested and verified for all with exception of binary relationship browser. #315 

closing this issue

**Comment by alexatrhea** [comment]
@MartinFijneman please check through this again when you have time.

**Comment by MartinFijneman** [comment]
was already covered, forgot to move to done, will correct that now.

Was tested again, still same results, only remaining issue is set in #315
