### ISSUE TITLE
Top element category info missing on option sheet

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#28]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

In the workbook, on the parameters sheet, the top element category information is given.
On the option sheets, this information is missing.

### Steps to Reproduce

* setup engineering model containing top element with one or more categories applied, and with multiple options
* open workbook and rebuild
* check category on parameters sheet: available
* check category info on option sheet: missing

### Logs

Not relevant
  - [X] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 1.0.13
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [X] Microsoft Excel (32/64 bit): 32-bit
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by samatrhea** [comment]
This seems to be an impediment to create budget sheets in excel
