### ISSUE TITLE
Fix CDP4ShellDialogs failing test

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#301]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The CDP4ShellDialogs  project contains a failing test that needs to be fixed. It is related to the `UriManagerViewModel` class

### Steps to Reproduce
run unit tests in CDP4ShellDialogs  project and notice failing test

### Logs
NA
  
### System Configuration
NA

**Comment by alexatrhea** [comment]
Cannot reproduce on either my PC or Mihail's. @samatrhea can you please re-check?
