### ISSUE TITLE
Setup CI/CD infrastructure for IME

### ISSUE THREAD

**Issue by alexatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#304]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Re-establish development environment with:

- Appveyor
- ~~Sonarqube~~

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [ ] CDP4-IME: 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by samatrhea** [comment]
@alexatrhea please add the DevExpress nuget feed here as well

**Comment by alexatrhea** [comment]
Devexpress retargetting in #414

**Comment by lxatrhea** [comment]
Unit tests are fixed and DevExpress 20.1.3 is fully implemented.

**Comment by alexatrhea** [comment]
#414 deals with appveyor. SonarQube will be moved to a seperate issue.
