### ISSUE TITLE
Create new engineering model from source not working

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#31]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Preparing demo activity for ITvitae on dedicated server, prepared an engineering model.

Creating another EM taking this as source model:
* model seemed to have been created, came up in list of engineering models
* trying to edit EM, to set from preparations to design study phase, received error message (item could not be found)
* disconnected and connected again, model no longer appearing in the list

### Steps to Reproduce

Not tried, problems on server under investigation

### Logs

  - [ ] There are no logs regarding the issue
  - [X] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 1.0.14
  - [ ] Other: 
  -
[CDP4IME - Create EM from source.log](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/2136203/CDP4IME.-.Create.EM.from.source.log)

- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [X] Microsoft Excel (32/64 bit): 32-bit
  - [X] Windows OS (32/64 bit): 32-bit
  - [ ] Additional information:

**Comment by samatrhea** [comment]
@MartinFijneman can you check if this still is an issue?

**Comment by naronatrhea** [comment]
this was working on version 1.0.21 of the IME coupled with version 1.0.11 (pré-release) of the web-service
