### ISSUE TITLE
Edit state to set to "forbidden" not possible in Edit actual finite state list dialog

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#32]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

editing a state (combination), to set from mandatory to forbidden or vice verssa, is not possible in the Edit actual finite state list dialog. This returns following message:
```
The CDP4 Services replied with code InternalServerError: Internal Server Error: "exception:Value cannot be null.\nParameter name: key"
```
Note that it is possible to edit individual states directly in the Finite states browser. The user is thus not stuck, it is only a little bit more involved.

### Steps to Reproduce

* within an engineering model, create a possible and actual state list with several states
* edit a resulting actual finite state list to open the Edit actual finite state list dialog
* in the box showing the actual finite states, select and edit the State Kind
Result: changing is 

### Logs

Tested on LOFT model on CDP4 public server

  - [ ] There are no logs regarding the issue
  - [X] I have attached a log file or included the relevant section in this issue  
  
[20180702 1337 CDP4IME.log](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/2155032/20180702.1337.CDP4IME.log)

### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 1.0.14
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by naron-rhea** [comment]
I could only reproduce the behaviour once on a almost fresh db (on which I have not done much). After that first fail, trying to re-update just works as expected.

I have then tried to reproduce again on a fresh db but without success.

It turns out that once updated on the database, the service tries to query that updated object but cannot find it which then throws a null-exception when calling the AfterUpdate method for that object.

We could make sure the queried object is not null before calling AfterUpdate (it should never be null).

Maybe a permission issue has filtered-out the object?

**Comment by MartinFijneman** [comment]
problem still occurs for me: not possible to change the satus of a state (mandatory/forbidden) in the editing dialog of the finite state list, see screenshot below:

![image](https://user-images.githubusercontent.com/35371313/77070825-3bd0eb80-69eb-11ea-99fb-ea652ff55867.png)

Moving item back to sprint backlog

**Comment by alexatrhea** [comment]
The `-dev` server has not been updated yet with the fix. We have seen it work on local latest versions.
