### ISSUE TITLE
CDP4-IME installation failure on Windows VM on OSX

### ISSUE THREAD

**Issue by jamiewhths** [RHEAGROUP/CDP4-IME-Community-Edition#320]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
User cannot install CDP4-IME on a Windows 7 Virtual Machine. Installation fails with the following error message, related to DevExpress:

![1_DevExpressError](https://user-images.githubusercontent.com/15144999/73641965-1f623500-4671-11ea-8879-c5d48f156b9b.png)

Running the installer as an administrator (Right click > Run as administrator) raises a slightly different error, but still related to DevExpress:

![2_01_InstallationError](https://user-images.githubusercontent.com/15144999/73642148-7831cd80-4671-11ea-8114-c5c7e48cd148.PNG)

![2_02_DevExpressError](https://user-images.githubusercontent.com/15144999/73642155-7a942780-4671-11ea-8490-9e14dff65ef0.PNG)

.NET Framework (V4.5.2) is successfully installed as part of the CDP4 installation process. 

### Steps to Reproduce
- Install VMWare Fusion on Mac OS X (see versions below)
- Load Windows 7 as Guest OS on VMWare
- Attempt to install latest version of CDP4-IME (with or without admin rights)

### Logs
  - [X] There are no logs regarding the issue 

No logs files have been collected from user, but can be requested.
  
### System Configuration

- CDP4 version:
  - CDP4-IME: 4.0.4 (32 bit); 5.0.3 (32 bit); 5.0.1 (64 bit) 

- Environment (Operating system, version and so on):
  - VM Platform: VMWare Fusion V8.1.0
  - Host OS: Mac OS 10.14.6 Mojave
  - Guest OS: Windows 7 V6.1 (Build 7600)

**Comment by samatrhea** [comment]
We successfully run the CDP4-IME using VMWare on windows 7 and windows 10. We have not yet tried this on an OSX host though. I did do some googling (the error message is not something we implemented) and i found the following link that describes the same problem: https://www.personalcomputerfixes.com/how-to-fix-error-2908-when-installing-programs-on-your-pc/  and here: http://microsoftask.com/2017/01/how-to-fix-microsoft-office-error-code-2908/

The DevExpress components are installed in the windows GAC and not in the same folder as the applicaiton. We can investigate whether installing next to the app solves the problem.

**Comment by jamiewhths** [comment]
I spotted a few support ticket on the DevExpress website which seem close to the error we're experiencing:
- https://www.devexpress.com/Support/Center/Question/Details/Q395986/exception-could-not-load-file-or-assembly-devexpress-xtralayout-v11-2-resources
- https://www.devexpress.com/Support/Center/Question/Details/Q494405/could-not-load-file-or-assembly-devexpress-xtrabars-v12-2-resources-version-12-2-8-0
- https://www.devexpress.com/Support/Center/Question/Details/T353732/could-not-load-file-or-assembly-devexpress-images-v15-1

**Comment by vikku12** [comment]
Try to install offline Office installation instead of network office installation. 

You can check this out to fix office error 1908 [https://msprofessionalchat.com/office-error-code-2908/](https://msprofessionalchat.com/office-error-code-2908/)

**Comment by samatrhea** [comment]
@jamiewhths is this still an issue?

**Comment by jamiewhths** [comment]
@samatrhea very sorry for the delayed response, very rarely log into GitHub these days. We got around the issue by using different virtualisation software and starting with fresh Windows 10 VM. We never found a way to fix the underlying issue from any of the external links or trying to repair installations.

**Comment by samatrhea** [comment]
@jamiewhths thanks for the feedback, in the mean-time we are also looking at getting CDP4 to run in Wine https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues/654
