### ISSUE TITLE
Error while deleting a default option

### ISSUE THREAD

**Issue by mmilitaru** [RHEAGROUP/CDP4-IME-Community-Edition#325]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Default option deletion in option iteration browser generates an error.

### Steps to Reproduce
Open Options iterations.
Create a new option and set it as default. Then try to delete that option. Deletion is being completed but an fatal error occurred and there is no more default option when we re-open the app.

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by samatrhea** [comment]
@mmilitaru Is the error produced by the server? or is it an error that occurs in the IME? Please add logs if you have them

**Comment by mmilitaru** [comment]
Yes, app crashes. And I think this is on the client when retried to setup the default option which is not found.

**Comment by samatrhea** [comment]
@mmilitaru Hi, can you provide log files please so we can go from an "I Think" to an "I know" please?
