### ISSUE TITLE
Deleting/ dragging a parameter cause a crash of the program.

### ISSUE THREAD

**Issue by oiynick** [RHEAGROUP/CDP4-IME-Community-Edition#33]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Deleting several parameters in a row from the Element Usage in Element Definition section cause crash of the program with an error dialog window.

### Steps to Reproduce
Was unable to reproduce the error.

### Logs

  - [ ] There are no logs regarding the issue
  - [x] I have attached a log file or included the relevant section in this issue  
  
[log.txt](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/2163148/log.txt)

### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 1.0.14 
  - [ ] Other: 
  
- Web Services:
  - [x] CDP4 Web Services version: 1.0.3 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [x] Windows OS (32/64 bit): Windows 10 Pro x64
  - [x] Additional information: Mac Bootcamp + Parallels Virtual Machine

**Comment by samatrhea** [comment]
@oiynick can you attach the log file as well?

**Comment by samatrhea** [comment]
We haven't been able to reproduce this problem for a long time now. I am therefore closing this issue. Please report a new issue when it appears again and please attach log files if you can.
