### ISSUE TITLE
Error opening Citation dialog

### ISSUE THREAD

**Issue by lxatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#331]
- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Citation dialog doesn't show because of an error.

Problem occurs in method PopulatePossibleSource in CDP4CommonView.ViewModels.CitationViewModel:

```
        protected override void PopulatePossibleSource()
        {
            this.PossibleSource.Clear();
            IEnumerable<ReferenceSource> referenceSources = null;
            var rdlsInChain = this.ChainOfContainer.Where(x => x is ReferenceDataLibrary).ToList();
            if (rdlsInChain.Any())
            {
                referenceSources = rdlsInChain.SelectMany(x => ((ReferenceDataLibrary)x).ReferenceSource);
            }

            this.PossibleSource.AddRange(referenceSources);
        }
```

Somehow, the ChainOfContainer property should contain a ReferenceDataLibrary.
In my local database that's not the case, so referenceSources variable is null.
That lets the AddRange method crash.

The crash should at least not be happening, but the reason that the ReferenceDataLibrary is not in ChainOfContainer (should it even be in there?) also has to be investigated.

### Steps to Reproduce
- Start a edit dialog that has a Definition tab (for example PossibleFiniteState edit dialog)
- Go to the Definitions tab
- Press the add button to add a Definition
- Select the Citation tab
- Press the add button to add a citation
- No Citation dialog is opened en the status bar shows that an error occurred

If the Citation dialog does show up, then I have a data issue locally, but then the PopulatePossibleSource method imho still needs some refactoring.

- CDP4 version:
  - [x] CDP4-IME: 5.1.1
  - [ ] Other:

**Comment by samatrhea** [comment]
The `ReferenceDataLibrary` only needs to be in the chain of containers in case the `DefinedThing` is contained in an RDL, e.g. a `ParameterType` . But, for `Things` that are contained by an `EngineeringModel` or by the `SiteDirectory` this does not hold true. So, @lxatrhea you are right, the code is not correct.

**Comment by lxatrhea** [comment]
@samatrhea So, if a DefinedThing is not contained in an RDL, a Citation cannot even be added to a Definition at all?
Is it then a good idea to also let the UI react on that, by disabling the add button in that case?

**Comment by samatrhea** [comment]
@lxatrhea i agree that this is a good approach.
