### ISSUE TITLE
ActualState order in ActualStateListDialog and Product/ElementDefinition trees.

### ISSUE THREAD

**Issue by alexatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#336]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Two issues:

- As possiblestatelist linked to actual state lists changes the order seems to be inconsistent between the list in the dialog and the nodes under the parameters in the product tree and element definition tree. The order shall be consistent.

- The nodes in the trees seem to be linked to the State, which means the context menu actions are linked to editing and deleting the state, which is incorrect. The actions should relate to the parent parameter. **(check if this is also the case for option dependent tree nodes and parameter components)**

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [ ] CDP4-IME: 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by kamilatrhea** [comment]
First issue is not reproducible, second issue is valid only for actual finite state in Product Tree, where context menu actions are directly link to editing actual state of parent parameter, what seems correctly .
