### ISSUE TITLE
CDP4 crash while selecting text in search field of parameter type browser

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#34]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Already noticed and reported in internal system earlier, on CDP4 EE v0.19 and CDP4 services (demo server), for that an older log file is included. 
A solution seems to have been implemented at the time, but now with CDP4 CE v1.0.14 this happened again, also during demonstration for other participant (no log file available however); therefore now reporting here.

Log file available:
* older log file for reference (20180208)
* log file of dedicated test on CDP4 public server, LOFT model (20180704)

### Steps to Reproduce

reproducible, see log file of 2nd event.
Didn't happen when parameter type browser is activated, and the search is used within this browser (tried with several actions).

Seems to happen when the parameter type browser itself is not active, and then the user tries to select the (data in the) search field directly. E.g. in the log file, the events leading to the crash at the end of the log file:
* open element definitions browser
* look for specific parameter using the search function (in this case TRL)
* drag and drop the parameter under the equipment base element definition
* with the mouse, without doing anything else try to select the text in the search field in the parameter type browser

With these steps, it should be reproducible.

Comments on proposed fix (February 2018):
* crash occurs when the selection of the text in the search field acts like a drag
* fix implemented based on suggestion made in https://github.com/punker76/gong-wpf-dragdrop/issues/54

This solution now needs to be inspected, since this doesn't seem to have solved the problem, or an additional problem occurs.

### Logs

  - [ ] There are no logs regarding the issue
  - [X] I have attached a log file or included the relevant section in this issue

Older log file for reference:
[20180208 1428CDP4IME -  crash after selection II.log](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/2163687/20180208.1428CDP4IME.-.crash.after.selection.II.log)
 
Current test to replicate issue:
[20180704 CDP4IME crash after selecting search field.log](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/2163713/20180704.CDP4IME.crash.after.selecting.search.field.log)

### System Configuration

- CDP4 version:
  - [X] CDP4-IME: v1.0.14
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): not relevant
  - [X] Windows OS (32/64 bit): for logged event 32-bit, for recent event on 64-bit, but with 32-bits version of CDP4 installer
  - [ ] Additional information:

**Comment by samatrhea** [comment]
fixed in b2ed5d9b894b8f6fe2ab3c92d6bb261a34b4d76c
