### ISSUE TITLE
Open model/iteration UI facelift

### ISSUE THREAD

**Issue by alexatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#342]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The open model views need to be refactored to make it easier to open a model/iteration combination. Now it is unclear to multiple users how the current open model logic works.

Opening a model needs to be refactored as follows:

1. a user clicks on the "open model" button on the ribbon
1. a modal dialog is presented that only shows a list of the available models (EngineeringModelSetup), lets include at least name, shortname and kind and allow the user to do text based search and do sorting/filtering in the list. The dialog shall include an Ok and Cancel button 
1. the user selects one of these models (double-click and/or ok button)
1. the user is presented with a modal dialog showing the iterations in the model as well as the domains of expertise the user can respresent. The domains of expertise shall be listed in a combobox. The default domain of the user shall be shown in bold and and be pre-selected. the other domains of expertise are sorted alphabetically. The iterations are sorted on date, the most recent one/active iteration is listed at the top and is pre-selected. The dialog shows an Ok and Cancel button.
1. when the user double clicks on an iteration and/or clicks on the Ok button the model/iteration is opened.

Alternatively to above, it may be possible to utilize one modal dialog with "wizard" like paging functionality. See for instance https://www.devexpress.com/Products/NET/Controls/WPF/Navigation/~app-navigation~wizard-control or look at other navigation options.

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [ ] CDP4-IME: 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by mmilitaru** [comment]
Search for a model must be done within multiple session. As per Sam suggestion will have a combo for session selection and a grid that display the models.

**Comment by alexatrhea** [comment]
Mist likely scenario is that you would search for model names.

**Comment by alexatrhea** [comment]
In not sure what you mean by models will be in a drop down and the selected will be the default.

**Comment by mmilitaru** [comment]
We search for a model and we select it. Next window will display iteration for that model. Yes, model will be just a label, not a combo.
