### ISSUE TITLE
Identify Mandatory plugins and set them as such in code and the installer.

### ISSUE THREAD

**Issue by alexatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#348]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
A feature to turn plugins on and off has been added, and in code the ability to mark plugins as mandatory has been created as well. There is need to identify which plugins are mandatory and implement this in the plugin attributes, as well as the installer.

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [ ] CDP4-IME: 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by samatrhea** [comment]
In the installer in the Product.wxs file there is an attribute called `Absent`, all seem to be set to `allow`, but i think this is not correct. Currently the NavigationService depends on the PROPERTYGRIDPLUGIN. as far as i can tell, this is the only one that is mandatory.
