### ISSUE TITLE
Re-Implement plugin loading based on settings

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#370]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The CDP4-IME and Excel Addin load plugins at startup from the plugin folder. The application settings infrastructure is used to load/save these settings. The following shall be taken into account when implementing this feature:

  - Plugins shall be loaded based on whether the plugin exists and it being enabled in the settings file
  - The IME and Add-In need to be independent from each other (different plugins being selected for each)
  - When a new release of the software is made, the plugin details (name, version number etc,) needs to be updated

### Steps to Reproduce
NA

### Logs
NA
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 6.0.0-RC2

**Comment by alexatrhea** [comment]
Another task:

- Set PropertyGrid to Mandatory in code.

**Comment by alexatrhea** [comment]
@lxatrhea I think we can close this
