### ISSUE TITLE
DiagramEditor - Incapability of creating a new diagram

### ISSUE THREAD

**Issue by nathanatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#396]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
On the DiagramBrowser, if the user select any of the diagram available, he won't be able to add a new one. Because having one diagram selected in this list disable the "add one diagram" button and the user is not able to deselect and make the "add one diagram" button enabled again. The only workaround right now is to re-open the DiagramBrowser.

### Steps to Reproduce
- Open the diagram browser from the diagram ribbon page ''Diagram'
- Select any existing diagram assuming there is any

### Logs

  - [x] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [ ] CDP4-IME: 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by alexatrhea** [comment]
This should be fixed by now
