### ISSUE TITLE
Migrate project files to VS2017 cpsroj files

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#43]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The current project files in the solution are still in the VS2015 format which is very verbose. It would be beneficial to move to a full 2017 csproj file setup

This article can be a good starting point: https://jumpforjoysoftware.com/2017/05/wpf-libraries-and-apps-under-new-csproj-format/

**Comment by lxatrhea** [comment]
Already fixed in another issue
