### ISSUE TITLE
 Implement the rest of functionalities of BatchEditor

### ISSUE THREAD

**Issue by nathanatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#433]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

features left to add as well as corresponding unit tests:

- [x] --action  remove-parameters 
- [x] --action  move-ref-to-manual-values 
- [x] --action  apply-option-dependence 
- [x] --action  apply-state-dependence
- [x] --action change-parameter-ownership 
- [x] --action change-domain
- [x] --action remove-option-dependence 
- [x] --action remove-state-dependence
- [x] --action set-generic-owners 
- [x] --action set-scale 
- [x] --action set-shape-scale-mm 
- [x] --action set-subscription-switch
- [x] report
- [x] subscription-switch

Not yet:
- --action standardise-for-cdf
- --action standardise-basic-parameters 
- --action standardise-groups

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [ ] CDP4-IME: 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by MartinFijneman** [comment]
verified, was already covered/ included earlier, mix-up in issues with #443 which has been included in RC4 tested below. this closed however as well

tested with:
CDP4-COMET version: 11.1.0 rc4
