### ISSUE TITLE
Parameters no longer appearing on option sheets when rebuilding

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#45]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

During preparation of a demo model, in the morning of 13/08 tested with rebuild in workbook, parameters appearing in the workbook on the option sheets as expected (testing a mass budget, this was working).
Continuing to build up the model in the morning, and later in the afternoon, and then trying to run the mass budget macro again, the parameters were not getting written on the option sheet anymore.

![image](https://user-images.githubusercontent.com/35371313/44101257-4cab23d2-9fe7-11e8-8205-e5680a1774f8.png)

Problem occuring for 2 models on the demo server:
* Marco Polo - original setup
* China Demo Space Design - towards the end of the afternoon, created as copy of the Marco Polo model during the setup

### Steps to Reproduce

* connect to demo server and log into any of the 2 EMs (Marco Polo or China Demo Space Design) in the workbook
* check the element definitions browser or product tree, for availability of parameters with subscriptions
* rebuild
Parameters are now not included on the option sheet, only top element and element usages

### Logs

  - [ ] There are no logs regarding the issue
  - [X] I have attached a log file or included the relevant section in this issue  
  
Note: Cut made for intermediate period, working on another unrelated server/model (so time gap in the log file).

[CDP4IME Parameters missing from option sheet.log](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/2287558/CDP4IME.Parameters.missing.from.option.sheet.log)

### System Configuration

- CDP4 version:
  - [X] CDP4-IME: first encounted with building up using 1.0.15, problem occurs as well with 1.0.16
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [X] Microsoft Excel (32/64 bit): 32
  - [X] Windows OS (32/64 bit): 32
  - [ ] Additional information:

**Comment by samatrhea** [comment]
@MartinFijneman : i have tried to reproduce this but cannot. I have logged representing the System DoE and can see many rows in excel that represent parameter subscriptions

**Comment by MartinFijneman** [comment]
reproducible problem in any case when adding more than 1 domain for a participant.
This situation leads to unexpected behaviour in excel, where the option sheets will show incorrect information for at least one of the domains.

**Comment by MartinFijneman** [comment]
Tested with version 1.0.19, issue still occurs

**Comment by MartinFijneman** [comment]
tested with version 1.0.20, fixed, closed
