### ISSUE TITLE
Possibility to filter on Categories in ElementDefinition browser

### ISSUE THREAD

**Issue by lxatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#465]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
At this moment we can filter the Element Definition browser on column values in the TreeList.
Category is not a column so we cannot filter the TreeList.
It would be good if we could filter the TreeList on Category.
This should be a multiselect implementation, so we can select multiple Categories.

**Comment by samatrhea** [comment]
@lxatrhea i think this can be closed because of the filter implementation you created
