### ISSUE TITLE
Value not kept when making parameter state dependent

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#47]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

testing on dev server:
value of parameter is not set as value for default state when parameter is made state dependent

### Steps to Reproduce

* have actual finite state list with states, one of which is set as default
* start with parameter with published value
* edit parameter to make state dependent

value from parameter is not set as value for default state

### Logs

  - [X] There are no logs regarding the issue
  - [ ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 1.0.18 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by samatrhea** [comment]
This is an issue on the server, reported here https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues/27

**Comment by naronatrhea** [comment]
this should have been fixed by ticket #27 server-side as mentioned by @samatrhea
