### ISSUE TITLE
Requirements - deleting a requirement group containing requirements caused crash

### ISSUE THREAD

**Issue by an-dream** [RHEAGROUP/CDP4-IME-Community-Edition#475]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
 Deleting requiremet groups (containing requirements) makes CDP4 crash. The contained requirement was present in the upper group/specification after reopening CDP4. However, the requirements tree layout was permanently altered (the rows of those items with a long description became larger) even after CDP4 restart.

### Steps to Reproduce

1. Create a requirement specification and add long description
2. Create a requirement group inside specification and add long description
3. Create a requirement inside group and add long description
4. Delete the group
5. This will cause crash so reopen CDP4
6. The requirement now appears directly inside the specification and the layout is permanently altered

### Logs

  - [x] There are no logs regarding the issue
  - [ ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 6.0.0 RC2
  - [ ] Other: 

- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [x] Windows OS (32/64 bit): 64 bit Windows 10
  - [ ] Additional information:

**Comment by MartinFijneman** [comment]
replicated on public server. Exception report and IME log:

[20200714 1734 CDP4IME - Issue 475.log](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/4919703/20200714.1734.CDP4IME.-.Issue.475.log)


[20200714 1734 Issue 475.txt](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/4919705/20200714.1734.Issue.475.txt)

**Comment by MartinFijneman** [comment]
verified, working correctly now: requirement kept when group is removed and is added to spec.
