### ISSUE TITLE
The data-source selection window does not allow a user to select the kind of data source, the combobox is empty

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#483]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The data-source selection window does not allow a user to select the kind of data source, the combobox is empty. The dal plugins are installed, so they should be visible to the app

![image](https://user-images.githubusercontent.com/22165725/86578834-b9117380-bf7c-11ea-83e8-fd89beb5b6d7.png)

I tried with the following draft release isntaller
https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/releases/tag/untagged-a31f539ecbd2638c3797

### Logs

  - [x] There are no logs regarding the issue
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: Version 6.0.0-RC4
  - [ ] Other: 
  -
- Web Services:
  - [x] Microsoft Excel (32/64 bit): 32
  - [x] Windows OS (32/64 bit): wind10 64bit

**Comment by lxatrhea** [comment]
Fixed in release 6.0.1
