### ISSUE TITLE
Second phase Grapher plugin implementation

### ISSUE THREAD

**Issue by lxatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#485]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Second phase of Grapher plugin implementation.
  - [x] Isolate => exit Isolation
  - [x] check if there's a element behind the mouse position
  - [x] Parameters
  - [x] Re-center view on redraw

**Comment by samatrhea** [comment]
i propose the following:

![image](https://user-images.githubusercontent.com/22165725/91295261-1666bb80-e79b-11ea-8649-740e72e41ae2.png)

Please have a look at the product tree how groups, parameters, overriders and subscriptions are displayed, if we can do this in a similar fashion that would be great.

**Comment by MartinFijneman** [comment]
include information similar to the tooltip text in the product tree
