### ISSUE TITLE
[RDL] RDL chain error related to ParameterType when copying element definitions from one model to another

### ISSUE THREAD

**Issue by an-dream** [RHEAGROUP/CDP4-IME-Community-Edition#487]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
 See the "Steps to Reproduce" below, as they make it easier to explain the issue.

### Steps to Reproduce

1. Create a Site RDL taking the Generic RDL as a source
2. Create two engineering models (one study model, the other model catalogue) and assign to them the newly created Site RDL
3. Create a parameter type having the new Site RDL as container
4. Create an element definition in the model catalogue
5. Add a parameter from the new RDL and one from the Generic RDL to the element definition
6. Drag and drop the element definition to the study model

The last action should have the effect of copying the element definition (together with its two parameters) from the model catalogue to the study model. Instead, an error is shown, saying that this action is forbidden, since the parameter type belonging to the Generic RDL is unavailable in the target model. This shouldn't be the case as the new Site RDL has the Generic RDL as a source.

### Logs

  - [ ] There are no logs regarding the issue
  - [ ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 6.0.0 RC2
  - [ ] Other: 
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [x] Windows OS (32/64 bit): 64 bits Windows 8
  - [ ] Additional information:

**Comment by MartinFijneman** [comment]
verified that there is a problem in the chain of RDLs for a newly created SiteRDL. The problem is a bit more generic. Tested on public server, with LOFT model available.

* create new SiteRDL
* create new Engineering model using SiteRDL
* open both new model and LOFT
* drag and drop ED from LOFT to model using other SiteRDL

This gives a similar error message

**Comment by samatrhea** [comment]
is the server complaining?

**Comment by lxatrhea** [comment]
WebService problem, so issue moved to WebService Repository.
