### ISSUE TITLE
deprecated items are always show, the show/hide deprecated items on the view ribbon is no longer working

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#49]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Deprecated items are hidden by default in all the views. A user can choose to show deprecated items by enabling the deprecated items on the view tab. Currently the deprecated items are always shown and the before mentioned show/hide button no longer works

### Steps to Reproduce
1. login to a server
2. open roles browser
3. verify that deprecated roles are shown

### Logs

  - [x] There are no logs regarding the issue  

### System Configuration

- CDP4 version:
  - [ ] CDP4-IME: 1.0.17

- Web Services: NA

**Comment by MartinFijneman** [comment]
verified with 1.0.19
