### ISSUE TITLE
Buttons too small in Close Iteration dialog

### ISSUE THREAD

**Issue by lxatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#493]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Buttons sized incorretly in the Close Iteration dialog
![image](https://user-images.githubusercontent.com/56023674/87395264-64d84600-c5b1-11ea-994d-f60981a40b39.png)

**Comment by MartinFijneman** [comment]
verified
