### ISSUE TITLE
Parameter ValueSet is saved to the wrong parameter

### ISSUE THREAD

**Issue by lxatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#496]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
A parameter's ValueSet can be saved to the wrong parameter.

### Steps to Reproduce
You need two users to reproduce:

UserA must have Auto refresh set 
1. UserA Sets starts editting a parameter's value in the ElementDefinition browser Tree and waits.
2. UserB adds a new element. Make sure that this new element changes the visible part of UserA's ElementDefinition browser Tree
### Logs
3. When Auto Refresh was executed for UserA, the tree gets rebuilt and the following happens:
    - The tree is redrawn.
    - Row focus is still on the formerly selected row.
    - The edit box however is drawn on the wrong row.
4. UserA selects another row (Click, or arrow keys) so the value will besaved
5. The value is saved to the wrong Parameter. 

In the example in the image below, we started editing the Manual Value of `electric current`.
After auto refresh the visual state of the tree is as in the image below.
After the edit box loses focus, the changed value is saved to the `currency` parameter.

![image](https://user-images.githubusercontent.com/56023674/87402568-0bc1df80-c5bc-11ea-8184-8e373eeee24b.png)

**Comment by MartinFijneman** [comment]
verified fixes, cancellation of changes properly working in case of incoming updates to tree/model structure in browser
