### ISSUE TITLE
Parameter subscriptions value sets not correctly created when copying item between models

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#51]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Item copied between engineering models (e.g. between catalogue and engineering model) is missing parameter subscription value sets.

### Steps to Reproduce

Starting conditions:
* 2 engineering models, A as source, B as target (e.g. a catalogue and an engineering model)
* source A has element definition with parameters of domain X
* parameters have subscriptions for domain(s) Y (Z,...) existing in both A and B
Then drag-and-drop element definition as domain X from source A to target B
* NOTE: precondition for this step is that domain X representative is able to create parameter subscriptions for other domains (e.g. being model administrator)

result:
* parameters are created in model B for domain X
* subscriptions for domain Y (e.g. in other client, or after close/open model) are missing value sets

### Logs

No log file available to share, but should be easily reproducible.

  - [X] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 1.0.18
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by naronatrhea** [comment]
this was a server issue. 
fixed by https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues/36
