### ISSUE TITLE
IME crash when adding parameter onto dashboard in iteration 2 of engineering model

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#511]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Within engineering model Release Test 6004 MF, created iteration 2. opened model for iteration 1 as well as for iteration 2, opened dashboard for both iteration 1 and iteration 2.
With these open, following steps:
* from ED browser for iteration 2, selected parameter (luminous intensity) from the ED "all parameter types with values"
* dropped parameter onto dashboard for iteration 2 (i.e. the correct iteration)

this caused an exception in the IME
exception report and log report available. IME log only set to level of warning

### Logs

  - [ ] There are no logs regarding the issue
  - [ X] I have attached a log file or included the relevant section in this issue  

[CDP4IME - exception in dashboard.log](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/4926710/CDP4IME.-.exception.in.dashboard.log)

[Exception report - drag parameter luminous intensity onto dashboard for Release Test 6004 MF iteration 2.txt](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/4926711/Exception.report.-.drag.parameter.luminous.intensity.onto.dashboard.for.Release.Test.6004.MF.iteration.2.txt)

  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 6.0.0.4
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by MartinFijneman** [comment]
additional testing: crash is reproducible when the frozen iteration 1 is opened as well. Then IME crashes when adding a parameter onto dashboard (from either one of the opened iterations)

**Comment by alexatrhea** [comment]
@MartinFijneman where is this model? Which server were you testing on?

**Comment by MartinFijneman** [comment]
verified, parameters can be added now, with only possible to drop parameters from corresponding iteration on dashboard
