### ISSUE TITLE
Grapher: Show the ElementDefinition's categories for ElemenUsages

### ISSUE THREAD

**Issue by lxatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#519]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
An ElementUsage "inherits" its ElemenDefinition's Categories.
ElemenDefinition's Categories therefore need to be shown in the Grapher tiles.

**Comment by samatrhea** [comment]
there is a convenience method in the CDP4-SDK that should take car of this
