### ISSUE TITLE
As a user i want to toggle the visibility of the SimpleParameterValue and ParametricConstraints in the Requirements treeview

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#53]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The requirements treeview currently shows a grouping for the SimpleParameterValues and ParametricConstraints . These overcrowd the view and it would be beneficial to hide these from view by default and enable on request (push of a button)

### Steps to Reproduce
NA

### Logs

  - [x] There are no logs regarding the issue
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 1.0.17

**Comment by samatrhea** [comment]
If possible, showing and hiding should be done with 2 buttons, one for SimpleParameterValues  and one for ParametricConstraints

**Comment by samatrhea** [comment]
Think about the usability of the specific rows:
 - do you still need folder grouping?
 - human readability of the parametric constraints needs to improve

**Comment by MartinFijneman** [comment]
verified, toggle availabe
