### ISSUE TITLE
SimpleParameterValue edit dialog - ParameterType combobx only shows shortname - difficult to read/interpret

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#54]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The SimpleParameterValue edito dialog shows a ParameterType combobx that only shows the shortname, this is difficult to read/interpret. The content should be replaced by **name [shortname]** and sorted alphabetically

### Steps to Reproduce
NA

### Logs

  - [x] There are no logs regarding the issue
  
### System Configuration

- CDP4 version:
  - [ ] CDP4-IME: 1.0.17

**Comment by samatrhea** [comment]
diff up @ http://phabricator.rheagroup.com/D1416

**Comment by MartinFijneman** [comment]
to me not clear which combobox in which dialog exactly is meant here, to be able to verify intended implementation of alphabetical ordering with name [shortname] notation

**Comment by samatrhea** [comment]
the ParameterType combobox on the edit dialog of a SimpleParameterValue

![image](https://user-images.githubusercontent.com/22165725/45108233-5b236300-b13c-11e8-8b84-2be08fc841c7.png)
