### ISSUE TITLE
The ActualValue column of the OptionSheets is hard-coded but should be linked to the cell on the Parameter Sheet

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#57]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The ActualValue column of the OptionSheets is hard-coded but should be linked to the cell on the Parameter Sheet. This allows a user to change the manual value on the Parametersheet without the need to rebuild the sheets

### Steps to Reproduce
NA

### Logs
NA
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 1.0.19

**Comment by MartinFijneman** [comment]
formatting issue on the option sheets, following parameters get a value representation instead of formatting:
* date
* time of day

**Comment by MartinFijneman** [comment]
testing implementation:
* option dependent parameters not appearing on option generated sheets

**Comment by MartinFijneman** [comment]
testing implementation:
* state dependent parameters are appearing, but with reference to (general) parameter, not the correct state dependent reference (e.g. formula appears as "ATS.area" resulting in a #REF error, instead of correct "ATS.area\A.S1" where "A.S1" is the shortname of state combination

**Comment by MartinFijneman** [comment]
testing implementation:
* where applicable, overrides are not taken over on option sheets with correct reference. Element definition reference is incorrectly used instead
