### ISSUE TITLE
Web context lost when WebServices are deployed in an specific context

### ISSUE THREAD

**Issue by javb-es** [RHEAGROUP/CDP4-IME-Community-Edition#571]
Dear colleagues,

The Plato Science Operations Centre at ESAC is trying to setup a CDP4 backend using the Webservices and Database Docker distributions.  This service is intended to support the Mission Parameter DB.

We've successfully installed and deployed the two Docker images in a local server inside our network.  In order to make the service available from the outside world, we have registered a public server in our DMZ in our ESA firewall with the following redirection:

<public.server.IP>/mdb redirects to <local.server.IP>:5000

From the web, it works.  We can access to <public.server.IP>/mdb/SiteDirectory and we get a response from the CDP4 Webservices.

From the CDP4 UI, it does not work.  We get a '503: Service Temporarily Unavailable' because the backend is redirecting to <public.server.IP>/app (the context /mdb is lost).

We think the CDP4 UI is assuming that the service is deployed directly in port 5000 and it's overwriting the web context redirecting to /app instead of to /mdb/app.  

Could you please analyse this issue?

We appreciate your time and help.

Best regards...

--

Antonio

**Comment by samatrhea** [comment]
@javb-es 

Can you let me know what versions you are using of the docker dbase, docker services and CDP4-IME? then we can investigate

Regards, Sam

**Comment by javb-es** [comment]
Hi Sam,

Versions below:

- cdp4-services-community-edition:4.0.0   
- cdp4-database-community-edition:2.0.0
- CDP4 IME 5.0.1.0

Regards...

**Comment by alexatrhea** [comment]
@javb-es We will need to take a closer look. It might be a problem in the services with the additional base path `/mdb` that you use. Typically we do not use this and install straight on a (sub-)domain. If that's a possibility for you it would be the quickest fix while we look into it on our end.

Meanwhile services v6.0.0 images have been released so please consider updating.

**Comment by javb-es** [comment]
Thanks for the quick reply.  We've upgraded to services 6.0.0:

(base) [ptouser@ptotest02 ~]$ docker container ls
CONTAINER ID        IMAGE                                             COMMAND                  CREATED             STATUS              PORTS                    NAMES
1072fbe27ca7        rheagroup/cdp4-services-community-edition:6.0.0   "/bin/bash /app/entr…"   12 minutes ago      Up 12 minutes       0.0.0.0:5000->5000/tcp   cdp4-services-community-edition
fae22a1ded2a        rheagroup/cdp4-database-community-edition:2.0.0   "docker-entrypoint.s…"   4 weeks ago         Up 4 weeks          0.0.0.0:5432->5432/tcp   cdp4-database-community-edition

The error from the UI still persists.

Indeed, we could ask ESA security to open port 5000 directly to the outside world, which it's not recommended and we are trying to avoid for security reasons.

Thanks again for your time.

Best regards...

**Comment by alexatrhea** [comment]
> Thanks for the quick reply. We've upgraded to services 6.0.0:
> 
> (base) [ptouser@ptotest02 ~]$ docker container ls
> CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
> 1072fbe27ca7 rheagroup/cdp4-services-community-edition:6.0.0 "/bin/bash /app/entr…" 12 minutes ago Up 12 minutes 0.0.0.0:5000->5000/tcp cdp4-services-community-edition
> fae22a1ded2a rheagroup/cdp4-database-community-edition:2.0.0 "docker-entrypoint.s…" 4 weeks ago Up 4 weeks 0.0.0.0:5432->5432/tcp cdp4-database-community-edition
> 
> The error from the UI still persists.
> 
> Indeed, we could ask ESA security to open port 5000 directly to the outside world, which it's not recommended and we are trying to avoid for security reasons.
> 
> Thanks again for your time.
> 
> Best regards...

I would not open port 5000 for the same reasons and I do not suggest that. What I do suggest is perhaps DNS entry and a reverse proxy like apache or nginx to resolve the mapping.

<public.server.dnsname>/SiteDirectory -> <local.server.ip>:5000/SiteDirectory

**Comment by samatrhea** [comment]
> 
> 
> > Thanks for the quick reply. We've upgraded to services 6.0.0:
> > (base) [ptouser@ptotest02 ~]$ docker container ls
> > CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
> > 1072fbe27ca7 rheagroup/cdp4-services-community-edition:6.0.0 "/bin/bash /app/entr…" 12 minutes ago Up 12 minutes 0.0.0.0:5000->5000/tcp cdp4-services-community-edition
> > fae22a1ded2a rheagroup/cdp4-database-community-edition:2.0.0 "docker-entrypoint.s…" 4 weeks ago Up 4 weeks 0.0.0.0:5432->5432/tcp cdp4-database-community-edition
> > The error from the UI still persists.
> > Indeed, we could ask ESA security to open port 5000 directly to the outside world, which it's not recommended and we are trying to avoid for security reasons.
> > Thanks again for your time.
> > Best regards...
> 
> I would not open port 5000 for the same reasons and I do not suggest that. What I do suggest is perhaps DNS entry and a reverse proxy like apache or nginx to resolve the mapping.
> 
> <public.server.dnsname>/SiteDirectory -> <local.server.ip>:5000/SiteDirectory

this is indeed how we expose servers to the web, we use a forward proxy such as NGINX or Apache where the cdp4services are running at `http://localhost:5000` and we expose them as `https://project-name.cdp4.org`

**Comment by javb-es** [comment]
Hi Sam,

Sorry for my late reply.

Indeed we are trying to do the same as you do to expose the web services:

You have them running at localhost:5000 and you expose them as https://project-name.cdp4.org.

The slight difference in our case is that we would like to have them exposed as https://project-name.cd4.org/mdb

And behind the scenes the services are removing /mdb and going directly to localhost:5000/app which we think is not correct.  The correct reference would be localhost:5000/mdb/app, somehow the underlying code is stripping out the context (if it exists) and assuming it's deployed at the ROOT context.  This is not necessary the case.

Thanks again for your time and support.

Best regards...

**Comment by lxatrhea** [comment]
First diagnose the problem and try to fix withing timebox.

**Comment by alexatrhea** [comment]
> Hi Sam,
> 
> Sorry for my late reply.
> 
> Indeed we are trying to do the same as you do to expose the web services:
> 
> You have them running at localhost:5000 and you expose them as https://project-name.cdp4.org.
> 
> The slight difference in our case is that we would like to have them exposed as https://project-name.cd4.org/mdb
> 
> And behind the scenes the services are removing /mdb and going directly to localhost:5000/app which we think is not correct. The correct reference would be localhost:5000/mdb/app, somehow the underlying code is stripping out the context (if it exists) and assuming it's deployed at the ROOT context. This is not necessarily the case.
> 
> Thanks again for your time and support.
> 
> Best regards...

Could you possibly provide us with the configuration of your proxy service (apache or nginx)? Of course, redact the irrelevant parts. We are interested in the proxy pass part.

**Comment by javb-es** [comment]
Hi Alex,
Find below the proxy configuration that we have.  Let us know if you require anything else from us.
Thanks in advance.
Best regards...

        ServerName      <ptotest02 public address>
        DocumentRoot    /var/www/html/ptotest02

        ProxyRequests     Off
        ProxyPreserveHost On

        ProxyPass        /mdb         http://<ptotest02 private address>:5000
        ProxyPassReverse /mdb         http://<ptotest02 private address>:5000

        ProxyPass        /         http://<ptotest02 private address>:8080/
        ProxyPassReverse /         http://<ptotest02 private address>:8080/

        CustomLog       /var/log/httpd/ptotest02-access_log combined
        ErrorLog        /var/log/httpd/ptotest02-error_log
        #LogLevel       warn

        BrowserMatch ".*MSIE.*" nokeepalive ssl-unclean-shutdown downgrade-1.0 force-response-1.0

        <Directory /var/www/html/ptotest02>
                AllowOverride none
                Order Allow,Deny
                Allow from all
        </Directory>

**Comment by alexatrhea** [comment]
@javb-es I have fixed the problem and verified with your apache configuration. I expect that the next RC of IME will contain the fix. We will notify you shortly about its availability, as we'd like to hear your feedback.

**Comment by javb-es** [comment]
Many thanks Alex, we'll provide feedback to you as soon as it's available to us.
Best regards...
