### ISSUE TITLE
Exception for CDP4 IME when publishing state dependent parameters

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#58]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Setting up a testing model, preparing element definitions with state dependent parameters.
Providing values for these parameters, published an initial set of parameters for the SYS domain.
While performing the publication, waiting for this to finish, the IME gave an exception, see below.

### Logs

  - [ ] There are no logs regarding the issue
  - [X] I have attached a log file or included the relevant section in this issue  
  CDP4 log files and exception report both available

[20180917 12.11 CDP4 IME exception report - crash at publishing state dependent values.txt](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/2388155/20180917.12.11.CDP4.IME.exception.report.-.crash.at.publishing.state.dependent.values.txt)

[20180917 1211 CDP4IME CDP4 IME Exception when publishing state dependent parameters.log](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/2388157/20180917.1211.CDP4IME.CDP4.IME.Exception.when.publishing.state.dependent.parameters.log)

### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 1.0.20
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [X] Microsoft Excel (32/64 bit): 32-bit
  - [X] Windows OS (32/64 bit): 32-bit
  - [ ] Additional information:

**Comment by naronatrhea** [comment]
I could not reproduce it on a fresh database populated with LOFT data updating for example the mass parameter of a Satellite Element-Definition
