### ISSUE TITLE
Create and document project structure

### ISSUE THREAD

**Issue by cozminvelciu** [RHEAGROUP/CDP4-IME-Community-Edition#592]
Based on the required functionality defined in #591, create a skeleton structure for the project containing all major components and interfaces (no implementation).

- [ ] create empty project(s)
- [ ] define and document project structure (components, modules, interfaces)
- [ ] create business logic implementation issues for each previously defined component

**Comment by alexatrhea** [comment]
Also needs a ribbon button for the Addin.

**Comment by cozminvelciu** [comment]
Based on the resulting skeleton structure for the project from this issue, additional tasks need to be created for each to-be-implemented component/module.

**Comment by cozminvelciu** [comment]
> Also needs a ribbon button for the Addin.

Ideally that should be implemented as part of the UI task.
