### ISSUE TITLE
Store / Retrieve filters

### ISSUE THREAD

**Issue by lxatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#597]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When a user creates a filter, would it be possible to store/retrieve filters? a potential solution can be to store these "named" filters in the Person.userPreference property

**Comment by alexatrhea** [comment]
Yes, this would be nice. Keep in mind that the applicable browser for a specific saved filter has to be stored most likely.
