### ISSUE TITLE
Grapher browser not opening

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#612]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

in testing VM, Grapher browser is not opening. The dropdown panel on the ribbon shows it as active browser, but the panel itself is not opened 

(testing on specific test model on dev server, request details if needed).

### Logs

  - [x] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 7.0.0 RC4
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by samatrhea** [comment]
@MartinFijneman can you provide the log files?

**Comment by MartinFijneman** [comment]
issue can be closed:

caused by version conflict due to dual installation of CE 7.x and EE 6.x, for which we can't really do anything (feedback Alex).

For separate installation (normal situation for users) it is working as expected.
