### ISSUE TITLE
Implement DomainOfExpertise filtering for initially displayed elements

### ISSUE THREAD

**Issue by cozminvelciu** [RHEAGROUP/CDP4-IME-Community-Edition#624]
The list initially displayed of elements (definitions or usages) from which the user can select should be filterable by domain of expertise.

Multi select dropdowns.
See the RelationshipMatrix project => Configuration view (right side).

**Comment by adrianchivu** [comment]
Because the list is replaced with the grid control, we can benefit by grid filtering option for "DomainOfExpertise" column in order to implement this.
