### ISSUE TITLE
IME exception in grapher while selecting item

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#652]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Testing the grapher on a testing model (Types Testing on DEV server), created a top element to have an option tree, then opened the grapher, and selected items on the diagram (randomly)
After 3 or 4 clicks (selecting other items), there was an exception.

no logs available, only exception report.

### Steps to Reproduce

tbd if reproducible, by opening model with option trees, opening grapher, and randomly selecting items on the diagram consecutively

### Logs

  - [ ] There are no logs regarding the issue
  - [X] I have attached a log file or included the relevant section in this issue  

[IME exception on grapher - selecting item.txt](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/5660810/IME.exception.on.grapher.-.selecting.item.txt)
  

### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 7.0.0 RC 5
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by MartinFijneman** [comment]
seems to be "reproducible" or in any case was able to get exception again by opening grapher (on LOFT model on the DEV server) and then scrolling on the diagram, with selecting various of the block on the diagram consecutively (random selection in terms of which block)

[IME exception on grapher - selecting item V2.txt](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/5660871/IME.exception.on.grapher.-.selecting.item.V2.txt)

**Comment by samatrhea** [comment]
@MartinFijneman Did the exception cause the CDP4-IME to crash, or could you continue working?

**Comment by MartinFijneman** [comment]
exception causing a crash.

still a problem now in testing for 700 RC7
