### ISSUE TITLE
Add calculation algorithm for p_mean ParameterType

### ISSUE THREAD

**Issue by cozminvelciu** [RHEAGROUP/CDP4-IME-Community-Edition#659]
The formula for p_mean can be found in the sample Excel sheet from ESA and the reasoning behind it will be provided by Johan Vennekens in an additional e-mail.

This calculation will be "hardcoded" in the Crossview generator specifically only for the "p_mean" ParameterType and will be linked back to the parameter sheet - see task #634 .

**Comment by adrianchivu** [comment]
### Alghoritm for computation of P_mean value:

P_stby (the power consumption when the equipment is in standby) 
P_on (The maximum power consumption when the equipment is working) 
P_duty_cycle (The fraction of the time the equipment is on in a particular system mode) (This parameter is state dependant) 
Redundancy (Compound parameter consisting of 4 different parameter types) 
        redundancy.scheme (Hot or cold) (Hot redundancy means all equipment are on, even the redundant ones. Cold redundancy means only the needed equipment are on) 
        redundancy.type (internal or external) ( Way of modelling the equipment. if all the redundancy is internal to the modelled equipment the scheme is internal, if the redundancy is external. ie more equipment modelled, the scheme is external) 
        redundancy.k (number of equipment needed) 
        redundancy.n (number of equipment in the satellite) 

The P_mean value is calculated in the following way. 
If the duty cycle is a -1, it is our convention that the equipment is OFF in that mode, and therefore the P_mean is 0. 
If the duty cycle is between 0 and 1. 
        - if the redundancy.type is internal. P_mean = P_duty_cycle*P_on+(1-P_duty_cyle)*P_stby 
        - if the redundancy.type is external and redundancy.scheme is cold  P_mean = (P_duty_cycle*P_on+(1-P_duty_cyle)*P_stby)*redundancy.k/redundancy.n 
        - if the redundancy.type is external and redundancy.scheme is hot  P_mean = P_duty_cycle*P_on+(1-P_duty_cyle)*P_stby 


### Excel formula computation of P_mean value:

=IFERROR(IF(ASI\redundancy.scheme\\="Passive (or Cold or standby)",IF(ASI\redundancy.type\\="External",ASI\redundancy.k\\/ASI\redundancy.n\\*IF(ASI\P_duty_cyc\PCM\>1,"-",IF(ASI\P_duty_cyc\PCM\<0,0,ASI\P_stby\\+ASI\P_duty_cyc\PCM\*(ASI\P_on\\-ASI\P_stby\\))),IF(ASI\P_duty_cyc\PCM\>1,"-",IF(ASI\P_duty_cyc\PCM\<0,0,ASI\P_stby\\+ASI\P_duty_cyc\PCM\*(ASI\P_on\\-ASI\P_stby\\))) ),IF(ASI\P_duty_cyc\PCM\>1,"-",IF(ASI\P_duty_cyc\PCM\<0,0,ASI\P_stby\\+ASI\P_duty_cyc\PCM\*(ASI\P_on\\-ASI\P_stby\\))) ),"-")

**Comment by cozminvelciu** [comment]
The hardcoded parameters should be the same as for the power report - order matters, same as in the power report:
1. redundancy (compound)
1. P_on
1. P_stby
1. P_peak
1. P_duty_cyc (state dependant)
1. P_mean (state dependant)

**Comment by cozminvelciu** [comment]
For the calculation we also need to check that P_duty_cyc and P_mean have the same state dependence.
