### ISSUE TITLE
Crossview editor - show selected scale in brackets, e.g. [kg], [m] etc.

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#678]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Crossview editor - show selected scale in brackets, e.g. [kg], [m] etc.

### Steps to Reproduce

scale is shown on the generated sheet. Align with parameter sheets and other cases in CDP4 by putting the scale in brackets:
length [m]
mass [kg]

### Logs

  - [x] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 6.0.0 RC7
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by cozminvelciu** [comment]
Done by #676.
