### ISSUE TITLE
Crossview editor - suggest to create sheet in active workbook (or have user selection)

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#690]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

the crossview is generated in a separate new workbook, and not in the workbook that you are starting from. 

request to add the sheet to the active/current workbook (would make sense to me) or have the user choose (which would be an extra step, so not preferred by me in any case)

### Logs

  - [x] There are no logs regarding the issue
  - [ ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 700 RC7
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by MartinFijneman** [comment]
could be that the problem comes from a wrong starting point in my testing approach: if the sheet is already in an active CDP4 workbook, it correctly gets updated in that workbook.
So unless I miss something that you know from the implementation, I think this issue can be closed.

**Comment by cozminvelciu** [comment]
I can't reproduce this in either of the following two scenarios:
1. New workbook
   * Starting from a new manually created workbook
   * Doing some manual changes to sheets/cells
   * Opening CDP4 and generating the Crossview
   * The Crossview sheet is correctly generated in the (active) workbook that I started from, not in a new workbook
1. CDP4 workbook
   * Starting from a workbook containing the parameter sheet generated with CDP4
   * Opening CDP4 and generating the Crossview
   * The Crossview sheet is correctly generated in the (active) workbook with the initial CDP4 parameter sheet data, not in a new workbook
