### ISSUE TITLE
Fix "add power parameter types" toggle button issues

### ISSUE THREAD

**Issue by adrianchivu** [RHEAGROUP/CDP4-IME-Community-Edition#719]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Fix the next problems with the "add power parameter types" toggle:
- After adding with the toggle, the clear ("eraser" button) does not reset toggle
- Trying to add again afterwards results in the toggle button doing nothing

**Comment by cozminvelciu** [comment]
This didn't work on my machine during the demo. Additional testing needed.

**Comment by adrianchivu** [comment]
@cozminvelciu do you add P_peak under selected element(s) ?

**Comment by cozminvelciu** [comment]
Indeed, if all (hardcoded) power parameters are not present, the toggle will not display "properly" - technically it's correct, but a bit confusing. If we receive feedback from ESA that they want this to look differently we can change it then.
