### ISSUE TITLE
Desktop App will not connect to Secure Server (https)

### ISSUE THREAD

**Issue by rkulshrestha** [RHEAGROUP/CDP4-IME-Community-Edition#733]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I have installed CDP4 webservices on our own servers using docker compose with nginx so that all requests get redirected to https. This setup has been verified using the browser and works. When I use the same data source details on Desktop App, I get the following error: `An error occured while sending the request`. I have checked the logs on the server to confirm that this request is not hitting the servers either. Using the Log Information panel ([log-cdp4.pdf](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/5915747/log-cdp4.pdf)), the step attached where it fails `CDP4Services Open C0E4D0263023: https://<servername>:443/SiteDirectory%3Fextent=deep&includeReferenceData=false` (Note: Actual Servername replaced) works fine when posted into a browser but fails on the app. 

The Desktop App however works fine with the public server that is available at: `https://cdp4services-public.rheagroup.com/`

`

### Logs

  - [ ] There are no logs regarding the issue
  - [x] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 7.0.0.8
  - [ ] Other: 
  -
- Web Services:
  - [x] CDP4 Web Services version: 6.0.0
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by samatrhea** [comment]
Dear @rkulshrestha, @alexatrhea 

I think this is due to the version of TLS you are using on your NGINX setup. The default for the .NET Framework we are using is the following: **SSLv3, TLSv1, and TLSv1.1.** We have a fix that solves this problem so that the CDP4 supports higher versions of TLS, but we will not be able to make a new release before the end of this week. The work around is to enable TLSv1, and TLSv1.1.

Let us know whether this helps. If this is not an option for you, then you will have to wait a couple of days until we can release CDP4 with the before-mentioned fixed.

**Comment by rkulshrestha** [comment]
> Dear @rkulshrestha, @alexatrhea
> 
> I think this is due to the version of TLS you are using on your NGINX setup. The default for the .NET Framework we are using is the following: **SSLv3, TLSv1, and TLSv1.1.** We have a fix that solves this problem so that the CDP4 supports higher versions of TLS, but we will not be able to make a new release before the end of this week. The work around is to enable TLSv1, and TLSv1.1.
> 
> Let us know whether this helps. If this is not an option for you, then you will have to wait a couple of days until we can release CDP4 with the before-mentioned fixed.

Hi @samatrhea @alexatrhea 

Thanks for that. I managed to enable **SSLv3, TLSv1, and TLSv1.1.** for now and it's working fine. Once you guys have released the version that supports higher versions of TLS, I will revert back the changes.

**Comment by samatrhea** [comment]
@rkulshrestha thank for letting us know. If you would be so kind to share the config changes you made then the rest of the CDP4 Community can benefit from that as well

**Comment by vessvass** [comment]
We had exactly the same issue using IME v11.0.0-rc8  and WEb services server  v.10.0.0. The solution was do downgrade nginx TLS from v1.3 to v1.2.
The baseline nginx cdp4-comet  definition e.g. as in https://comet.io.esa.int/content/8-setup/00-index.html  was used, with our  standard additional security headers (as for all our nginx servers)
