### ISSUE TITLE
Missing margins on module level

### ISSUE THREAD

**Issue by cozminvelciu** [RHEAGROUP/CDP4-IME-Community-Edition#740]
### Description
[referring to mass reports]: There are currently no margins on module level. (ie, Payload module level)

**Comment by lxatrhea** [comment]
@cozminvelciu The way it is build at the moment, this value is expected at the second System, or the Second Elements level within the Product Tree. If this data can be found at another level then the report needs to be changed.

**Comment by cozminvelciu** [comment]
> @cozminvelciu The way it is build at the moment, this value is expected at the second System, or the Second Elements level within the Product Tree. If this data can be found at another level then the report needs to be changed.

@lxatrhea I've sent an email to Johan trying to schedule a meeting for this week to discuss these issues.

**Comment by cozminvelciu** [comment]
The missing margins on module level were caused by the parameter missing on the proper Element in the model.

However, there was a (different) small change requested by Johan: that when this margin is present on the module level, it should be included (and displayed) in the calculation only for the module total (and above: grand total, etc.) - and not in the mass of each element.

These module totals should make clear that they include the margin (maybe rename the displayed column name to "mass + margin" - currently it's called "mass [kg]").

**Comment by lxatrhea** [comment]
@cozminvelciu : I added a new row in the System group header if a mass parameter is found at the 2nd system level.

![afbeelding](https://user-images.githubusercontent.com/56023674/109295159-8c251000-782e-11eb-9673-1b6b02514949.png)
