### ISSUE TITLE
 [ElementDefinitions] As a user I would like to create Element Definitions Groups/Folders

### ISSUE THREAD

**Issue by an-dream** [RHEAGROUP/CDP4-IME-Community-Edition#750]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
As a user I would like to create Element Definitions Groups/Folders at "Element Definition Level", not as part of the containment.

This could be useful (as a quicker alternative to filters) to organize the "lego bricks" into folders inside a Model Catalogue (e.g. folder with all generic equipment, folder with all RWs from a supplier) and in a Study Model (e.g. folder with all equipment related to AOCS).

### Logs

  - [x] There are no logs regarding the issue
  - [ ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 7.0.0
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [x] Microsoft Excel (32/64 bit): 64bit
  - [x] Windows OS (32/64 bit): Windows 10, 64 bit
  - [ ] Additional information:

**Comment by samatrhea** [comment]
This requires an update to E-TM-10-25 that has been discussed in the past with ESA which at the time was discarded. I doubt this will be implemented any time soon. The category-filter approach is the way forward.
