### ISSUE TITLE
Duplicate value sets for subscription after copying ED within same model

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#76]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Setting up a model, preparing modelling items in a catalogue model.

Within the catalogue model, copied an element definition with subscriptions.

For the copied item, error message for the domain that has subscriptions on the copied parameters

Errors
Duplicated value-sets were found for the option - and state -

### Steps to Reproduce

Setup catalogue model with element definition, parameter
Set subscription for other domain
Copy the element definition
This led to error for subscribing domain

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [ ] CDP4-IME: 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by alexatrhea** [comment]
Issue with WebServices: https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/issues/40
