### ISSUE TITLE
As a user i want to create an ElementUsage by means of drag-n-drop from the ElementDefinition browser into the product tree

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#77]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
As a user i want to create an ElementUsage by means of drag-n-drop from the ElementDefinition browser into the product tree. This will make it more obvious where the user wants to creat a usage and will cause less scrolling in the ElementDefinition browser

### Steps to Reproduce
NA

### Logs
NA
  
### System Configuration

- CDP4 version:
  - [ ] CDP4-IME: 1.0.23

**Comment by naronatrhea** [comment]
Considering the support of 10-25 for decomposition level deeper than 1, the user will have to be careful when doing that.
