### ISSUE TITLE
As a user i want to be able to filter the ParameterTypes with user defined frequently parametertypes

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#79]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
In order to allow a user to filter the visible ParameterTypes in the ParameterTypes browser, allow a user to make a selection of frequently used parametertypes. This list can be stored in the user-preferences on the Person class

### Logs

  - [x] There are no logs regarding the issue
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 1.0.23

**Comment by MartinFijneman** [comment]
verified, working as expected. including with setting as deprecated/un-deprecated, with show and hide these (all sorts of switching and changing settings)
