### ISSUE TITLE
satsearch integration - search on category field doesn't return any results

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#8]
### Prerequisites

- [X ] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
CDP4 IME satsearch integration: using search functionality on category (through drop-down list) doesn't return any results

### Steps to Reproduce
* connect to satsearch database
* search any other field to check correct connection (i.e. providing at least some relevant results)
* clear search
* search using category field

### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 1.0.8.0
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by samatrhea** [comment]
Currently the plugin shows what are called "top level categories", the satsearch API does not support searching on these, only on the subcategories. The fix will be an extra combox that will be populated with the sub categories of the selected topcategory
