### ISSUE TITLE
User defined ordering of RequirementSpecifications, RequirementGroups and Requirements

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#83]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
10-25 does not have explicit support for ordering of RequirementSpecification, RequirementGroups and Requirements within a spec or group. In the GUI the sorting is done based on shortname and this leads to very silly shortnames to get some sort of user-defined ordering in place. This is not a vialbe solution.

A user should be able to determine the order by means of drag-n-drop. The only problem is that 10-25 does not support ordering out of the box. I propose to find a solution where ordering is possible without changing the data-model. Therefore i propose to make use of a SimpleParameterValue on these items to achieve this Goal. When a requirement is moved, then the SimpleParameterValue that represents the sort-key needs to be updated. When a requirement is created a SimpleParameterValue for the sort-key needs to be created as well. I propose we use a settings file for the requirements-plugin where we can specificy the unique identifier of the parametertype that should be sued. If this does not exist in the chain of RDL's, then ordering is not supported and the `SimpleParameterValue` is ignored.

The SimpleParameterValue that is used for sorting should probaby not be shown by default to the user (perhaps a setting might be usefull to choose to see it and potetially edit it manually to fix something?)

### Logs

  - [ ] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [ ] CDP4-IME: 
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by naronatrhea** [comment]
if the user knows that a requirement is sorted by its short-name isnt it ok to leave the naming scheme to him?
A requirement usually have an identifier which is set as the shortname in 10-25. Is it so bad to use it as the sorting criteria?

**Comment by samatrhea** [comment]
there are a couple of problems with using the shortname for ordering:
  - pretty cumbersome if you want to reorganize after you have a decent set. May mean changing the human readable identifier all over the place, and in the end, even though it can be changed, you could argue that these need to remain stable. 
  - allow a user to re-order by means of drag-n-drop is a better user experience to re-order than editing fields
