### ISSUE TITLE
Requirements browser - all items ownership should be filtered for active domains in EM

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#84]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of the CDP4-IME
- [ ] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Requirements browser - all items ownership should be filtered for active domains in EM

Requirements and all related concepts in the requirements browser show the full list of domains, and these can be set as owner as well.
The owner field should be filtered on active domains in the engineering model, only active domains allowed to own requirements, requirement groups etc.

### Steps to Reproduce

have EM with limited number of active domains
create requirement for non-active domain

### Logs

  - [X] There are no logs regarding the issue
  - { ] I have attached a log file or included the relevant section in this issue  
  
### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 1.0.23
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [ ] Microsoft Excel (32/64 bit): 
  - [ ] Windows OS (32/64 bit): 
  - [ ] Additional information:

**Comment by naronatrhea** [comment]
the list of possible domain shuold only show the active domain for the model
