### ISSUE TITLE
When a new requirement is created, activate the edit field where the requirement text is entered

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#85]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When a requirement dialog is popped the OK button is disabled untill all mandatory fields have been populated, To make it more apparent to the user tha ta requirement text should be entered, the requirement description field should be enabled for editing by default (on add only, not necessary for edit/inspect)

### Steps to Reproduce
NA

### Logs

  - [x] There are no logs regarding the issue
  
### System Configuration

- CDP4 version:
  - [ ] CDP4-IME: 1.0.23

**Comment by naronatrhea** [comment]
fixed along #88
