### ISSUE TITLE
drag-n-drop of ElementDefinition to Option Tree creates ElementUsage at incorrect level

### ISSUE THREAD

**Issue by samatrhea** [RHEAGROUP/CDP4-IME-Community-Edition#97]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the CDP4-IME
- [x] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When a user wants to create a usage by drag-n-drop of an ElementDefinition into an option tree, the resulting ElementUsage is at the incorrect level.

### Steps to Reproduce
- Open ElementDefinitionTree, open an Option tree
- multiple elementdefinitions exist and an option tree with 3 or 4 levels exists
- Drag-n-drop an ElementDefintion on a nested usage in the option tree
- note that an ElementUsage is created, but that this usage is not nested in the target of the drop action, but at the same level.

### Logs

  - [x] There are no logs regarding the issue
  
### System Configuration

- CDP4 version:
  - [x] CDP4-IME: 2.0.2

- Web Services:
  - [x] CDP4 Web Services version: 3.1.0

**Comment by MartinFijneman** [comment]
verified

Closing this issue and setting to done
