### ISSUE TITLE
Exception while publishing items and creating subscription

### ISSUE THREAD

**Issue by MartinFijneman** [RHEAGROUP/CDP4-IME-Community-Edition#99]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Exception while performing publish action and continuing to set subscriptions on parameters

### Steps to Reproduce

TBD if reproducible

### Logs

  - [] There are no logs regarding the issue
  - [X] I have attached a log file or included the relevant section in this issue  
 
attached exception report

[20190312 14.15 publishing items and creating subscription.txt](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/files/2956989/20190312.14.15.publishing.items.and.creating.subscription.txt)

### System Configuration

- CDP4 version:
  - [X] CDP4-IME: 2.0.2
  - [ ] Other: 
  -
- Web Services:
  - [ ] CDP4 Web Services version: 
  - [ ] OCDT WSP version: 
- Environment (Operating system, version and so on):
  - [X] Microsoft Excel (32/64 bit): 32
  - [X] Windows OS (32/64 bit): 64
  - [ ] Additional information:

**Comment by mmilitaru** [comment]
The issue could not be reproduced. Please provide clear steps of the error or verify this is no longer an issue.

**Comment by MartinFijneman** [comment]
Performed several tests on public server, have not been able to reproduce with various combinations: various parameter types, option dependency, state dependency, option and state dependency, setting subscriptions on parameters waiting to be published, parameters that have just been published etc.
All working as expected.

Will therefore close issue as not reproducable
